/*
 RequireJS 0.2.1 Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/jrburke/requirejs for details
 RequireJS i18n Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/jrburke/requirejs for details
 RequireJS text Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/jrburke/requirejs for details
 RequireJS order Copyright (c) 2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/jrburke/requirejs for details

 jQuery JavaScript Library v1.4.4
 http://jquery.com/

 Copyright 2010, John Resig
 Dual licensed under the MIT or GPL Version 2 licenses.
 http://jquery.org/license

 Includes Sizzle.js
 http://sizzlejs.com/
 Copyright 2010, The Dojo Foundation
 Released under the MIT, BSD, and GPL Licenses.

 Date: Thu Nov 11 19:04:53 2010 -0500
*/
var require,define;
(function(){function P(x){return S.call(x)==="[object Function]"}function A(x){return S.call(x)==="[object Array]"}function xa(x,C,K){for(var Q in C)if(!(Q in ka)&&(!(Q in x)||K))x[Q]=C[Q];return H}function Z(x,C,K){var Q,$,R;for(Q=0;R=C[Q];Q++){R=typeof R==="string"?{name:R}:R;$=R.location;if(K&&(!$||$.indexOf("/")!==0&&$.indexOf(":")===-1))R.location=K+"/"+(R.location||R.name);R.location=R.location||R.name;R.lib=R.lib||"lib";R.main=R.main||"main";x[R.name]=R}}function J(x){function C(m,q){var w;
if(m.charAt(0)===".")if(q){if(O.config.packages[q])q=[q];else{q=q.split("/");q=q.slice(0,q.length-1)}m=q.concat(m.split("/"));for(w=0;q=m[w];w++)if(q==="."){m.splice(w,1);w-=1}else if(q==="..")if(w===1)break;else if(w>1){m.splice(w-1,2);w-=2}m=m.join("/")}return m}function K(m,q){var w=m?m.indexOf("!"):-1,D=null;if(w!==-1){D=m.substring(0,w);m=m.substring(w+1,m.length)}if(m)m=C(m,q);if(D){D=C(D,q);D=ab[D]||D}return{prefix:D,name:m,parentName:q,fullName:D?D+"!"+m:m}}function Q(){var m=true,q=la.priorityWait,
w,D;if(q){for(D=0;w=q[D];D++)if(!oa[w]){m=false;break}m&&delete la.priorityWait}return m}function $(m){if(!O.jQuery)if((m=m||(typeof jQuery!=="undefined"?jQuery:null))&&"readyWait"in m){O.jQuery=m;if(!V.jquery&&!O.jQueryDef)V.jquery=m;if(O.scriptCount){m.readyWait+=1;O.jQueryIncremented=true}}}function R(m){return function(q){m.exports=q}}function Oa(m,q){return function(){var w=[].concat(ca.call(arguments,0));w.push(q);return m.apply(null,w)}}function bb(m){var q=Oa(O.require,m);xa(q,{nameToUrl:Oa(O.nameToUrl,
m),toUrl:Oa(O.toUrl,m),isDefined:Oa(O.isDefined,m),ready:H.ready,isBrowser:H.isBrowser});return q}function cb(m){var q=m.prefix,w=m.fullName;if(!(Ja[w]||w in V)){if(q){O.plugins[q]=undefined;cb(K(q))}O.paused.push(m)}}function Ua(m){var q,w,D;q=m.callback;var I=m.fullName;D=[];var aa=m.depArray;if(q&&P(q)){if(aa)for(q=0;q<aa.length;q++)D.push(m.deps[aa[q]]);w=H.execCb(I,m.callback,D);if(I)if(m.usingExports&&w===undefined&&(!m.cjsModule||!("exports"in m.cjsModule)))w=V[I];else if(m.cjsModule&&"exports"in
m.cjsModule)w=V[I]=m.cjsModule.exports;else{if(I in V&&!m.usingExports)return H.onError(new Error(I+" has already been defined"));V[I]=w}}else if(I)w=V[I]=q;if(I)if(D=Aa[I]){for(q=0;q<D.length;q++)D[q].onDep(I,w);delete Aa[I]}if(Da[m.waitId]){delete Da[m.waitId];m.isDone=true;O.waitCount-=1;if(O.waitCount===0)Va=[]}}function db(m,q,w,D){var I=K(m,D);m=I.name;var aa=I.fullName,ba={waitId:m||ma+jb++,depCount:0,depMax:0,prefix:I.prefix,name:m,fullName:aa,deps:{},depArray:q,callback:w,onDep:function(eb,
kb){if(!(eb in ba.deps)){ba.deps[eb]=kb;ba.depCount+=1;ba.depCount===ba.depMax&&Ua(ba)}}},ia;if(aa){if(aa in V||oa[aa]===true)return;Ja[aa]=true;oa[aa]=true;O.jQueryDef=aa==="jquery"}for(w=0;w<q.length;w++)if(I=q[w]){I=K(I,m||D);ia=I.fullName;q[w]=ia;if(ia==="require")ba.deps[ia]=bb(m);else if(ia==="exports"){ba.deps[ia]=V[aa]={};ba.usingExports=true}else if(ia==="module"){ba.cjsModule=I=ba.deps[ia]={id:m,uri:m?O.nameToUrl(m,null,D):undefined};I.setExports=R(I)}else if(ia in V&&!(ia in Da))ba.deps[ia]=
V[ia];else{ba.depMax+=1;cb(I);(Aa[ia]||(Aa[ia]=[])).push(ba)}}if(ba.depCount===ba.depMax)Ua(ba);else{Da[ba.waitId]=ba;Va.push(ba);O.waitCount+=1}}function Pa(m){db.apply(null,m);oa[m[0]]=true}function Wa(m,q){if(!m.isDone){var w=m.fullName,D=m.depArray,I,aa;if(w){if(q[w])return V[w];q[w]=true}for(aa=0;aa<D.length;aa++)(I=D[aa])&&!m.deps[I]&&Da[I]&&m.onDep(I,Wa(Da[I],q));return w?V[w]:undefined}}function Ga(){var m=la.waitSeconds*1E3,q=m&&O.startTime+m<(new Date).getTime();m="";var w=false,D=false,
I;if(la.priorityWait)if(Q())Ka();else return;for(I in oa)if(!(I in ka)){w=true;if(!oa[I])if(q)m+=I+" ";else{D=true;break}}if(w||O.waitCount){if(q&&m){I=new Error("require.js load timeout for modules: "+m);I.requireType="timeout";I.requireModules=m;return H.onError(I)}if(D||O.scriptCount){if(da||pa)setTimeout(Ga,50)}else if(O.waitCount){for(Ea=0;m=Va[Ea];Ea++)Wa(m,{});Ga()}else H.checkReadyState()}}function Xa(m,q){var w=q.name,D=q.fullName;if(!(D in V)){Qa[m]||(Qa[m]=V[m]);oa[D]||(oa[D]=false);Qa[m].load(w,
bb(q.parentName),function(I){require.onPluginLoad&&require.onPluginLoad(O,m,w,I);Ua({prefix:q.prefix,name:q.name,fullName:q.fullName,callback:I});oa[D]=true},la)}}function fb(m){var q=m.prefix,w=m.fullName;if(!(Ja[w]||w in V)){Ja[w]=true;if(q)if(V[q])Xa(q,m);else{if(!La[q]){La[q]=[];(Aa[q]||(Aa[q]=[])).push({onDep:function(D){if(D===q){var I=La[q];for(D=0;D<I.length;D++)Xa(q,I[D]);delete La[q]}}})}La[q].push(m)}else H.load(O,w)}}var O,Ka,la={waitSeconds:7,baseUrl:ea.baseUrl||"./",paths:{},packages:{}},
Ha=[],Ja={require:true,exports:true,module:true},V={},oa={},Da={},Va=[],jb=0,Aa={},Qa={},La={};Ka=function(){var m,q,w;if(O.scriptCount<=0)O.scriptCount=0;for(;Ha.length;){m=Ha.shift();if(m[0]===null)return H.onError(new Error("Mismatched anonymous require.def modules"));else Pa(m)}if(!(la.priorityWait&&!Q())){for(;O.paused.length;){w=O.paused;O.paused=[];for(q=0;m=w[q];q++)fb(m);O.startTime=(new Date).getTime()}Ga()}};O={contextName:x,config:la,defQueue:Ha,waiting:Da,waitCount:0,specified:Ja,loaded:oa,
scriptCount:0,urlFetched:{},defined:V,paused:[],plugins:Qa,managerCallbacks:Aa,splitPrefix:K,normalizeName:C,configure:function(m){var q,w,D;if(m.baseUrl)if(m.baseUrl.charAt(m.baseUrl.length-1)!=="/")m.baseUrl+="/";q=la.paths;w=la.packages;xa(la,m,true);if(m.paths){for(D in m.paths)D in ka||(q[D]=m.paths[D]);la.paths=q}if((q=m.packagePaths)||m.packages){if(q)for(D in q)D in ka||Z(w,q[D],D);m.packages&&Z(w,m.packages);la.packages=w}if(m.priority){O.require(m.priority);la.priorityWait=m.priority}if(m.deps||
m.callback)O.require(m.deps||[],m.callback);m.ready&&H.ready(m.ready)},isDefined:function(m,q){return K(m,q).fullName in V},require:function(m,q,w){if(typeof m==="string"){if(H.get)return H.get(O,m,q);w=q;if(m==="require"||m==="exports"||m==="module")return H.onError(new Error("Explicit require of "+m+" is not allowed."));q=K(m,w);m=V[q.fullName];if(m===undefined)return H.onError(new Error("require: module name '"+q.fullName+"' has not been loaded yet for context: "+x));return m}for(db(null,m,q,w);!O.scriptCount&&
O.paused.length;)Ka()},completeLoad:function(m){var q;if(v.length){Ba.apply(O.defQueue,[O.defQueue.length-1,0].concat(v));v=[]}for(;Ha.length;){q=Ha.shift();if(q[0]===null){q[0]=m;break}else if(q[0]===m)break;else{Pa(q);q=null}}q?Pa(q):Pa([m,[],m==="jquery"&&typeof jQuery!=="undefined"?function(){return jQuery}:null]);oa[m]=true;$();if(H.isAsync)O.scriptCount-=1;Ka();H.isAsync||(O.scriptCount-=1)},toUrl:function(m,q){var w=m.lastIndexOf("."),D=null;if(w!==-1){D=m.substring(w,m.length);m=m.substring(0,
w)}return O.nameToUrl(m,D,q)},nameToUrl:function(m,q,w){var D,I,aa,ba,ia=O.config;m=C(m,w);if(H.jsExtRegExp.test(m))m=m+(q?q:"");else{D=ia.paths;I=ia.packages;w=m.split("/");for(ba=w.length;ba>0;ba--){aa=w.slice(0,ba).join("/");if(D[aa]){w.splice(0,ba,D[aa]);break}else if(aa=I[aa]){D=aa.location+"/"+aa.lib;if(m===aa.name)D+="/"+aa.main;w.splice(0,ba,D);break}}m=w.join("/")+(q||".js");m=(m.charAt(0)==="/"||m.match(/^\w+:/)?"":ia.baseUrl)+m}return ia.urlArgs?m+((m.indexOf("?")===-1?"?":"&")+ia.urlArgs):
m}};O.jQueryCheck=$;O.resume=Ka;return O}function W(){var x,C,K;if(c&&c.readyState==="interactive")return c;x=document.getElementsByTagName("script");for(C=x.length-1;C>-1&&(K=x[C]);C--)if(K.readyState==="interactive")return c=K;return null}var L=/(\/\*([\s\S]*?)\*\/|\/\/(.*)$)/mg,T=/require\(["']([\w\!\-_\.\/]+)["']\)/g,S=Object.prototype.toString,ja=Array.prototype,ca=ja.slice,Ba=ja.splice,da=!!(typeof window!=="undefined"&&navigator&&document),pa=!da&&typeof importScripts!=="undefined",ya=da&&
navigator.platform==="PLAYSTATION 3"?/^complete$/:/^(complete|loaded)$/,ma="_r@@",ka={},qa={},v=[],c=null,Ca=false,gb=false,ab={text:"require/text",i18n:"require/i18n",order:"require/order"},H,sa={},Ya,ea,Fa,Ra,Ia,Ma,ta,hb,Sa,Ea,Za,$a;if(typeof require!=="undefined")if(P(require))return;else sa=require;H=require=function(x,C,K){var Q="_",$;if(!A(x)&&typeof x!=="string"){$=x;if(A(C)){x=C;C=K}else x=[]}if($&&$.context)Q=$.context;K=qa[Q]||(qa[Q]=J(Q));$&&K.configure($);return K.require(x,C)};H.version=
"0.2.1";H.isArray=A;H.isFunction=P;H.mixin=xa;H.jsExtRegExp=/^\/|:|\?|\.js$/;ea=H.s={contexts:qa,skipAsync:{},isPageLoaded:!da,readyCalls:[]};if(H.isAsync=H.isBrowser=da){Fa=ea.head=document.getElementsByTagName("head")[0];if(Ra=document.getElementsByTagName("base")[0])Fa=ea.head=Ra.parentNode}H.onError=function(x){throw x;};H.load=function(x,C){var K=x.contextName,Q=x.urlFetched,$=x.loaded;Ca=false;$[C]||($[C]=false);$=x.nameToUrl(C);if(!Q[$]){x.scriptCount+=1;H.attach($,K,C);Q[$]=true;if(x.jQuery&&
!x.jQueryIncremented){x.jQuery.readyWait+=1;x.jQueryIncremented=true}}};define=H.def=function(x,C,K){var Q;if(typeof x!=="string"){K=C;C=x;x=null}if(!H.isArray(C)){K=C;C=[]}if(!x&&!C.length&&H.isFunction(K))if(K.length){K.toString().replace(L,"").replace(T,function($,R){C.push(R)});C=["require","exports","module"].concat(C)}if(gb){Q=Ya||W();if(!Q)return H.onError(new Error("ERROR: No matching script interactive for "+K));x||(x=Q.getAttribute("data-requiremodule"));Q=qa[Q.getAttribute("data-requirecontext")]}(Q?
Q.defQueue:v).push([x,C,K])};H.execCb=function(x,C,K){return C.apply(null,K)};H.onScriptLoad=function(x){var C=x.currentTarget||x.srcElement,K;if(x.type==="load"||ya.test(C.readyState)){c=null;x=C.getAttribute("data-requirecontext");K=C.getAttribute("data-requiremodule");qa[x].completeLoad(K);C.removeEventListener?C.removeEventListener("load",H.onScriptLoad,false):C.detachEvent("onreadystatechange",H.onScriptLoad)}};H.attach=function(x,C,K,Q,$){var R;if(da){Q=Q||H.onScriptLoad;R=document.createElement("script");
R.type=$||"text/javascript";R.charset="utf-8";R.async=!ea.skipAsync[x];R.setAttribute("data-requirecontext",C);R.setAttribute("data-requiremodule",K);if(R.addEventListener)R.addEventListener("load",Q,false);else{gb=true;R.attachEvent("onreadystatechange",Q)}R.src=x;Ya=R;Ra?Fa.insertBefore(R,Ra):Fa.appendChild(R);Ya=null;return R}else if(pa){Q=qa[C];C=Q.loaded;C[K]=false;importScripts(x);Q.completeLoad(K)}return null};ea.baseUrl=sa.baseUrl;if(da&&(!ea.baseUrl||!Fa)){ja=document.getElementsByTagName("script");
Ma=sa.baseUrlMatch?sa.baseUrlMatch:/(requireplugins-|require-)?jquery[\-\d\.]*(min)?\.js(\W|$)/i;for(Ea=ja.length-1;Ea>-1&&(Ia=ja[Ea]);Ea--){if(!Fa)Fa=Ia.parentNode;if(!Sa&&(Sa=Ia.getAttribute("data-main"))){sa.deps=sa.deps?sa.deps.concat(Sa):[Sa];if(!sa.baseUrl&&(ta=Ia.src)){ta=ta.split("/");ta.pop();ea.baseUrl=sa.baseUrl=ta.length?ta.join("/"):"./"}}if(!ea.baseUrl&&(ta=Ia.src))if(hb=ta.match(Ma)){ea.baseUrl=ta.substring(0,hb.index);break}}}H.pageLoaded=function(){if(!ea.isPageLoaded){ea.isPageLoaded=
true;Za&&clearInterval(Za);if($a)document.readyState="complete";H.callReady()}};H.checkReadyState=function(){var x=ea.contexts,C;for(C in x)if(!(C in ka))if(x[C].waitCount)return;ea.isDone=true;H.callReady()};H.callReady=function(){var x=ea.readyCalls,C,K,Q;if(ea.isPageLoaded&&ea.isDone){if(x.length){ea.readyCalls=[];for(C=0;K=x[C];C++)K()}x=ea.contexts;for(Q in x)if(!(Q in ka)){C=x[Q];if(C.jQueryIncremented){C.jQuery.readyWait-=1;C.jQueryIncremented=false}}}};H.ready=function(x){ea.isPageLoaded&&
ea.isDone?x():ea.readyCalls.push(x);return H};if(da){if(document.addEventListener){document.addEventListener("DOMContentLoaded",H.pageLoaded,false);window.addEventListener("load",H.pageLoaded,false);if(!document.readyState){$a=true;document.readyState="loading"}}else if(window.attachEvent){window.attachEvent("onload",H.pageLoaded);if(self===self.top)Za=setInterval(function(){try{if(document.body){document.documentElement.doScroll("left");H.pageLoaded()}}catch(x){}},30)}document.readyState==="complete"&&
H.pageLoaded()}H(sa);typeof setTimeout!=="undefined"&&setTimeout(function(){var x=ea.contexts[sa.context||"_"];x.jQueryCheck();x.scriptCount||x.resume();H.checkReadyState()},0)})();
(function(){function P(Z,J,W,L,T,S){if(J[Z]){W.push(Z);if(J[Z]===true||J[Z]===1)L.push(T+Z+"/"+S)}}function A(Z,J,W,L,T){J=L+J+"/"+T;require._fileExists(Z.nameToUrl(J,null))&&W.push(J)}var xa=/(^.*(^|\/)nls(\/|$))([^\/]*)\/?([^\/]*)/;define("require/i18n",{load:function(Z,J,W,L){L=L||{};var T=xa.exec(Z),S=T[1],ja=T[4],ca=T[5],Ba=ja.split("-"),da=[],pa={},ya,ma,ka="";if(T[5]){S=T[1];Z=S+ca}else{Z=Z;ca=T[4];ja=L.locale||(L.locale=typeof navigator==="undefined"?"root":(navigator.language||navigator.userLanguage||
"root").toLowerCase());Ba=ja.split("-")}if(require.isBuild){da.push(Z);A(J,"root",da,S,ca);for(ya=0;ma=Ba[ya];ya++){ka+=(ka?"-":"")+ma;A(J,ka,da,S,ca)}J(da);W()}else J([Z],function(qa){var v=[];P("root",qa,v,da,S,ca);for(ya=0;ma=Ba[ya];ya++){ka+=(ka?"-":"")+ma;P(ka,qa,v,da,S,ca)}J(da,function(){var c,Ca;for(c=v.length-1;c>-1&&(ma=v[c]);c--){Ca=qa[ma];if(Ca===true||Ca===1)Ca=J(S+ma+"/"+ca);require.mixin(pa,Ca)}W(pa)})})}})})();
(function(){var P=["Msxml2.XMLHTTP","Microsoft.XMLHTTP","Msxml2.XMLHTTP.4.0"],A=/^\s*<\?xml(\s)+version=[\'\"](\d)*.(\d)*[\'\"](\s)*\?>/im,xa=/<body[^>]*>\s*([\s\S]+)\s*<\/body>/im,Z=[];if(!require.textStrip)require.textStrip=function(J){if(J){J=J.replace(A,"");var W=J.match(xa);if(W)J=W[1]}else J="";return J};if(!require.jsEscape)require.jsEscape=function(J){return J.replace(/(['\\])/g,"\\$1").replace(/[\f]/g,"\\f").replace(/[\b]/g,"\\b").replace(/[\n]/g,"\\n").replace(/[\t]/g,"\\t").replace(/[\r]/g,
"\\r")};if(!require.getXhr)require.getXhr=function(){var J,W,L;if(typeof XMLHttpRequest!=="undefined")return new XMLHttpRequest;else for(W=0;W<3;W++){L=P[W];try{J=new ActiveXObject(L)}catch(T){}if(J){P=[L];break}}if(!J)throw new Error("require.getXhr(): XMLHttpRequest not available");return J};if(!require.fetchText)require.fetchText=function(J,W){var L=require.getXhr();L.open("GET",J,true);L.onreadystatechange=function(){L.readyState===4&&W(L.responseText)};L.send(null)};define("require/text",{load:function(J,
W,L,T){var S=false,ja=null,ca=J.indexOf("."),Ba=J.substring(0,ca),da=J.substring(ca+1,J.length);ca=da.indexOf("!");if(ca!==-1){S=da.substring(ca+1,da.length);da=da.substring(0,ca);ca=S.indexOf("!");if(ca!==-1&&S.substring(0,ca)==="strip"){ja=S.substring(ca+1,S.length);S="strip"}else if(S!=="strip"){ja=S;S=null}}if(ja!==null)L(ja);else{W=W.nameToUrl(Ba,"."+da);require.fetchText(W,function(pa){pa=S?require.textStrip(pa):pa;if(require.isBuild&&T.inlineText)Z[J]=pa;L(pa)})}},onWrite:function(J,W,L){if(W in
Z){var T=require.jsEscape(Z[W]);L("define('"+J+"!"+W+"', function () { return '"+T+"';});\n")}}})})();
(function(){function P(L,T,S){T([L],function(ja){S(function(){return ja})})}function A(L){var T=L.currentTarget||L.srcElement,S;if(L.type==="load"||Z.test(T.readyState)){L=T.getAttribute("data-requiremodule");W[L]=true;for(L=0;S=J[L];L++)if(W[S.name])P(S.name,S.req,S.onLoad);else break;L>0&&J.splice(0,L);setTimeout(function(){T.parentNode.removeChild(T)},15)}}var xa=typeof document!=="undefined"&&typeof window!=="undefined"&&(document.createElement("script").async||window.opera&&Object.prototype.toString.call(window.opera)===
"[object Opera]"||"MozAppearance"in document.documentElement.style),Z=/^(complete|loaded)$/,J=[],W={};define("require/order",{load:function(L,T,S){var ja=T.nameToUrl(L,null);if(require.isBuild)P(L,T,S);else{require.s.skipAsync[ja]=true;if(xa)T([L],function(ca){S(function(){return ca})});else if(T.isDefined(L))T([L],function(ca){S(function(){return ca})});else{J.push({name:L,req:T,onLoad:S});require.attach(ja,"",L,A,"script/cache")}}}})})();
(function(P,A){function xa(a,b,d){if(d===A&&a.nodeType===1){d=a.getAttribute("data-"+b);if(typeof d==="string"){try{d=d==="true"?true:d==="false"?false:d==="null"?null:!c.isNaN(d)?parseFloat(d):gb.test(d)?c.parseJSON(d):d}catch(e){}c.data(a,b,d)}else d=A}return d}function Z(){return false}function J(){return true}function W(a,b,d){d[0].type=a;return c.event.handle.apply(b,d)}function L(a){var b,d,e,f,h,l,k,o,z,u,F,N=[];f=[];h=c.data(this,this.nodeType?"events":"__events__");if(typeof h==="function")h=
h.events;if(!(a.liveFired===this||!h||!h.live||a.button&&a.type==="click")){if(a.namespace)F=new RegExp("(^|\\.)"+a.namespace.split(".").join("\\.(?:.*\\.)?")+"(\\.|$)");a.liveFired=this;var ga=h.live.slice(0);for(k=0;k<ga.length;k++){h=ga[k];h.origType.replace(Ma,"")===a.type?f.push(h.selector):ga.splice(k--,1)}f=c(a.target).closest(f,a.currentTarget);o=0;for(z=f.length;o<z;o++){u=f[o];for(k=0;k<ga.length;k++){h=ga[k];if(u.selector===h.selector&&(!F||F.test(h.namespace))){l=u.elem;e=null;if(h.preType===
"mouseenter"||h.preType==="mouseleave"){a.type=h.preType;e=c(a.relatedTarget).closest(h.selector)[0]}if(!e||e!==l)N.push({elem:l,handleObj:h,level:u.level})}}}o=0;for(z=N.length;o<z;o++){f=N[o];if(d&&f.level>d)break;a.currentTarget=f.elem;a.data=f.handleObj.data;a.handleObj=f.handleObj;F=f.handleObj.origHandler.apply(f.elem,arguments);if(F===false||a.isPropagationStopped()){d=f.level;if(F===false)b=false;if(a.isImmediatePropagationStopped())break}}return b}}function T(a,b){return(a&&a!=="*"?a+".":
"")+b.replace(hb,"`").replace(Sa,"&")}function S(a){return!a||!a.parentNode||a.parentNode.nodeType===11}function ja(a,b,d){if(c.isFunction(b))return c.grep(a,function(f,h){return!!b.call(f,h,f)===d});else if(b.nodeType)return c.grep(a,function(f){return f===b===d});else if(typeof b==="string"){var e=c.grep(a,function(f){return f.nodeType===1});if(Ua.test(b))return c.filter(b,e,!d);else b=c.filter(b,e)}return c.grep(a,function(f){return c.inArray(f,b)>=0===d})}function ca(a){return c.nodeName(a,"table")?
a.getElementsByTagName("tbody")[0]||a.appendChild(a.ownerDocument.createElement("tbody")):a}function Ba(a,b){var d=0;b.each(function(){if(this.nodeName===(a[d]&&a[d].nodeName)){var e=c.data(a[d++]),f=c.data(this,e);if(e=e&&e.events){delete f.handle;f.events={};for(var h in e)for(var l in e[h])c.event.add(this,h,e[h][l],e[h][l].data)}}})}function da(a,b){b.src?c.ajax({url:b.src,async:false,dataType:"script"}):c.globalEval(b.text||b.textContent||b.innerHTML||"");b.parentNode&&b.parentNode.removeChild(b)}
function pa(a,b,d){var e=b==="width"?a.offsetWidth:a.offsetHeight;if(d==="border")return e;c.each(b==="width"?m:q,function(){d||(e-=parseFloat(c.css(a,"padding"+this))||0);if(d==="margin")e+=parseFloat(c.css(a,"margin"+this))||0;else e-=parseFloat(c.css(a,"border"+this+"Width"))||0});return e}function ya(a,b,d,e){if(c.isArray(b)&&b.length)c.each(b,function(f,h){d||rb.test(a)?e(a,h):ya(a+"["+(typeof h==="object"||c.isArray(h)?f:"")+"]",h,d,e)});else if(!d&&b!=null&&typeof b==="object")c.isEmptyObject(b)?
e(a,""):c.each(b,function(f,h){ya(a+"["+f+"]",h,d,e)});else e(a,b)}function ma(a,b){var d={};c.each(ob.concat.apply([],ob.slice(0,b)),function(){d[this]=a});return d}function ka(a){if(!lb[a]){var b=c("<"+a+">").appendTo("body"),d=b.css("display");b.remove();if(d==="none"||d==="")d="block";lb[a]=d}return lb[a]}function qa(a){return c.isWindow(a)?a:a.nodeType===9?a.defaultView||a.parentWindow:false}var v=P.document,c=function(){function a(){if(!b.isReady){try{v.documentElement.doScroll("left")}catch(j){setTimeout(a,
1);return}b.ready()}}var b=function(j,s){return new b.fn.init(j,s)},d=P.jQuery,e=P.$,f,h=/^(?:[^<]*(<[\w\W]+>)[^>]*$|#([\w\-]+)$)/,l=/\S/,k=/^\s+/,o=/\s+$/,z=/\W/,u=/\d/,F=/^<(\w+)\s*\/?>(?:<\/\1>)?$/,N=/^[\],:{}\s]*$/,ga=/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,B=/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,fa=/(?:^|:|,)(?:\s*\[)+/g,ua=/(webkit)[ \/]([\w.]+)/,g=/(opera)(?:.*version)?[ \/]([\w.]+)/,i=/(msie) ([\w.]+)/,n=/(mozilla)(?:.*? rv:([\w.]+))?/,p=navigator.userAgent,r=false,
t=[],E,G=Object.prototype.toString,X=Object.prototype.hasOwnProperty,ra=Array.prototype.push,va=Array.prototype.slice,wa=String.prototype.trim,U=Array.prototype.indexOf,Na={};b.fn=b.prototype={init:function(j,s){var y,M;if(!j)return this;if(j.nodeType){this.context=this[0]=j;this.length=1;return this}if(j==="body"&&!s&&v.body){this.context=v;this[0]=v.body;this.selector="body";this.length=1;return this}if(typeof j==="string")if((y=h.exec(j))&&(y[1]||!s))if(y[1]){M=s?s.ownerDocument||s:v;if(j=F.exec(j))if(b.isPlainObject(s)){j=
[v.createElement(j[1])];b.fn.attr.call(j,s,true)}else j=[M.createElement(j[1])];else{j=b.buildFragment([y[1]],[M]);j=(j.cacheable?j.fragment.cloneNode(true):j.fragment).childNodes}return b.merge(this,j)}else{if((s=v.getElementById(y[2]))&&s.parentNode){if(s.id!==y[2])return f.find(j);this.length=1;this[0]=s}this.context=v;this.selector=j;return this}else if(!s&&!z.test(j)){this.selector=j;this.context=v;j=v.getElementsByTagName(j);return b.merge(this,j)}else return!s||s.jquery?(s||f).find(j):b(s).find(j);
else if(b.isFunction(j))return f.ready(j);if(j.selector!==A){this.selector=j.selector;this.context=j.context}return b.makeArray(j,this)},selector:"",jquery:"1.4.4",length:0,size:function(){return this.length},toArray:function(){return va.call(this,0)},get:function(j){return j==null?this.toArray():j<0?this.slice(j)[0]:this[j]},pushStack:function(j,s,y){var M=b();b.isArray(j)?ra.apply(M,j):b.merge(M,j);M.prevObject=this;M.context=this.context;if(s==="find")M.selector=this.selector+(this.selector?" ":
"")+y;else if(s)M.selector=this.selector+"."+s+"("+y+")";return M},each:function(j,s){return b.each(this,j,s)},ready:function(j){b.bindReady();if(b.isReady)j.call(v,b);else t&&t.push(j);return this},eq:function(j){return j===-1?this.slice(j):this.slice(j,+j+1)},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},slice:function(){return this.pushStack(va.apply(this,arguments),"slice",va.call(arguments).join(","))},map:function(j){return this.pushStack(b.map(this,function(s,y){return j.call(s,
y,s)}))},end:function(){return this.prevObject||b(null)},push:ra,sort:[].sort,splice:[].splice};b.fn.init.prototype=b.fn;b.extend=b.fn.extend=function(){var j,s,y,M,ha,Y=arguments[0]||{},na=1,za=arguments.length,mb=false;if(typeof Y==="boolean"){mb=Y;Y=arguments[1]||{};na=2}if(typeof Y!=="object"&&!b.isFunction(Y))Y={};if(za===na){Y=this;--na}for(;na<za;na++)if((j=arguments[na])!=null)for(s in j){y=Y[s];M=j[s];if(Y!==M)if(mb&&M&&(b.isPlainObject(M)||(ha=b.isArray(M)))){if(ha){ha=false;y=y&&b.isArray(y)?
y:[]}else y=y&&b.isPlainObject(y)?y:{};Y[s]=b.extend(mb,y,M)}else if(M!==A)Y[s]=M}return Y};b.extend({noConflict:function(j){P.$=e;if(j)P.jQuery=d;return b},isReady:false,readyWait:1,ready:function(j){j===true&&b.readyWait--;if(!b.readyWait||j!==true&&!b.isReady){if(!v.body)return setTimeout(b.ready,1);b.isReady=true;if(!(j!==true&&--b.readyWait>0))if(t){var s=0,y=t;for(t=null;j=y[s++];)j.call(v,b);b.fn.trigger&&b(v).trigger("ready").unbind("ready")}}},bindReady:function(){if(!r){r=true;if(v.readyState===
"complete")return setTimeout(b.ready,1);if(v.addEventListener){v.addEventListener("DOMContentLoaded",E,false);P.addEventListener("load",b.ready,false)}else if(v.attachEvent){v.attachEvent("onreadystatechange",E);P.attachEvent("onload",b.ready);var j=false;try{j=P.frameElement==null}catch(s){}v.documentElement.doScroll&&j&&a()}}},isFunction:function(j){return b.type(j)==="function"},isArray:Array.isArray||function(j){return b.type(j)==="array"},isWindow:function(j){return j&&typeof j==="object"&&"setInterval"in
j},isNaN:function(j){return j==null||!u.test(j)||isNaN(j)},type:function(j){return j==null?String(j):Na[G.call(j)]||"object"},isPlainObject:function(j){if(!j||b.type(j)!=="object"||j.nodeType||b.isWindow(j))return false;if(j.constructor&&!X.call(j,"constructor")&&!X.call(j.constructor.prototype,"isPrototypeOf"))return false;var s;for(s in j);return s===A||X.call(j,s)},isEmptyObject:function(j){for(var s in j)return false;return true},error:function(j){throw j;},parseJSON:function(j){if(typeof j!==
"string"||!j)return null;j=b.trim(j);if(N.test(j.replace(ga,"@").replace(B,"]").replace(fa,"")))return P.JSON&&P.JSON.parse?P.JSON.parse(j):(new Function("return "+j))();else b.error("Invalid JSON: "+j)},noop:function(){},globalEval:function(j){if(j&&l.test(j)){var s=v.getElementsByTagName("head")[0]||v.documentElement,y=v.createElement("script");y.type="text/javascript";if(b.support.scriptEval)y.appendChild(v.createTextNode(j));else y.text=j;s.insertBefore(y,s.firstChild);s.removeChild(y)}},nodeName:function(j,
s){return j.nodeName&&j.nodeName.toUpperCase()===s.toUpperCase()},each:function(j,s,y){var M,ha=0,Y=j.length,na=Y===A||b.isFunction(j);if(y)if(na)for(M in j){if(s.apply(j[M],y)===false)break}else for(;ha<Y;){if(s.apply(j[ha++],y)===false)break}else if(na)for(M in j){if(s.call(j[M],M,j[M])===false)break}else for(y=j[0];ha<Y&&s.call(y,ha,y)!==false;y=j[++ha]);return j},trim:wa?function(j){return j==null?"":wa.call(j)}:function(j){return j==null?"":j.toString().replace(k,"").replace(o,"")},makeArray:function(j,
s){s=s||[];if(j!=null){var y=b.type(j);j.length==null||y==="string"||y==="function"||y==="regexp"||b.isWindow(j)?ra.call(s,j):b.merge(s,j)}return s},inArray:function(j,s){if(s.indexOf)return s.indexOf(j);for(var y=0,M=s.length;y<M;y++)if(s[y]===j)return y;return-1},merge:function(j,s){var y=j.length,M=0;if(typeof s.length==="number")for(var ha=s.length;M<ha;M++)j[y++]=s[M];else for(;s[M]!==A;)j[y++]=s[M++];j.length=y;return j},grep:function(j,s,y){var M=[],ha;y=!!y;for(var Y=0,na=j.length;Y<na;Y++){ha=
!!s(j[Y],Y);y!==ha&&M.push(j[Y])}return M},map:function(j,s,y){for(var M=[],ha,Y=0,na=j.length;Y<na;Y++){ha=s(j[Y],Y,y);if(ha!=null)M[M.length]=ha}return M.concat.apply([],M)},guid:1,proxy:function(j,s,y){if(arguments.length===2)if(typeof s==="string"){y=j;j=y[s];s=A}else if(s&&!b.isFunction(s)){y=s;s=A}if(!s&&j)s=function(){return j.apply(y||this,arguments)};if(j)s.guid=j.guid=j.guid||s.guid||b.guid++;return s},access:function(j,s,y,M,ha,Y){var na=j.length;if(typeof s==="object"){for(var za in s)b.access(j,
za,s[za],M,ha,y);return j}if(y!==A){M=!Y&&M&&b.isFunction(y);for(za=0;za<na;za++)ha(j[za],s,M?y.call(j[za],za,ha(j[za],s)):y,Y);return j}return na?ha(j[0],s):A},now:function(){return(new Date).getTime()},uaMatch:function(j){j=j.toLowerCase();j=ua.exec(j)||g.exec(j)||i.exec(j)||j.indexOf("compatible")<0&&n.exec(j)||[];return{browser:j[1]||"",version:j[2]||"0"}},browser:{}});b.each("Boolean Number String Function Array Date RegExp Object".split(" "),function(j,s){Na["[object "+s+"]"]=s.toLowerCase()});
p=b.uaMatch(p);if(p.browser){b.browser[p.browser]=true;b.browser.version=p.version}if(b.browser.webkit)b.browser.safari=true;if(U)b.inArray=function(j,s){return U.call(s,j)};if(!/\s/.test("\u00a0")){k=/^[\s\xA0]+/;o=/[\s\xA0]+$/}f=b(v);if(v.addEventListener)E=function(){v.removeEventListener("DOMContentLoaded",E,false);b.ready()};else if(v.attachEvent)E=function(){if(v.readyState==="complete"){v.detachEvent("onreadystatechange",E);b.ready()}};return P.jQuery=P.$=b}();(function(){c.support={};var a=
v.documentElement,b=v.createElement("script"),d=v.createElement("div"),e="script"+c.now();d.style.display="none";d.innerHTML="   <link/><table></table><a href='/a' style='color:red;float:left;opacity:.55;'>a</a><input type='checkbox'/>";var f=d.getElementsByTagName("*"),h=d.getElementsByTagName("a")[0],l=v.createElement("select"),k=l.appendChild(v.createElement("option"));if(!(!f||!f.length||!h)){c.support={leadingWhitespace:d.firstChild.nodeType===3,tbody:!d.getElementsByTagName("tbody").length,
htmlSerialize:!!d.getElementsByTagName("link").length,style:/red/.test(h.getAttribute("style")),hrefNormalized:h.getAttribute("href")==="/a",opacity:/^0.55$/.test(h.style.opacity),cssFloat:!!h.style.cssFloat,checkOn:d.getElementsByTagName("input")[0].value==="on",optSelected:k.selected,deleteExpando:true,optDisabled:false,checkClone:false,scriptEval:false,noCloneEvent:true,boxModel:null,inlineBlockNeedsLayout:false,shrinkWrapBlocks:false,reliableHiddenOffsets:true};l.disabled=true;c.support.optDisabled=
!k.disabled;b.type="text/javascript";try{b.appendChild(v.createTextNode("window."+e+"=1;"))}catch(o){}a.insertBefore(b,a.firstChild);if(P[e]){c.support.scriptEval=true;delete P[e]}try{delete b.test}catch(z){c.support.deleteExpando=false}a.removeChild(b);if(d.attachEvent&&d.fireEvent){d.attachEvent("onclick",function u(){c.support.noCloneEvent=false;d.detachEvent("onclick",u)});d.cloneNode(true).fireEvent("onclick")}d=v.createElement("div");d.innerHTML="<input type='radio' name='radiotest' checked='checked'/>";
a=v.createDocumentFragment();a.appendChild(d.firstChild);c.support.checkClone=a.cloneNode(true).cloneNode(true).lastChild.checked;c(function(){var u=v.createElement("div");u.style.width=u.style.paddingLeft="1px";v.body.appendChild(u);c.boxModel=c.support.boxModel=u.offsetWidth===2;if("zoom"in u.style){u.style.display="inline";u.style.zoom=1;c.support.inlineBlockNeedsLayout=u.offsetWidth===2;u.style.display="";u.innerHTML="<div style='width:4px;'></div>";c.support.shrinkWrapBlocks=u.offsetWidth!==
2}u.innerHTML="<table><tr><td style='padding:0;display:none'></td><td>t</td></tr></table>";var F=u.getElementsByTagName("td");c.support.reliableHiddenOffsets=F[0].offsetHeight===0;F[0].style.display="";F[1].style.display="none";c.support.reliableHiddenOffsets=c.support.reliableHiddenOffsets&&F[0].offsetHeight===0;u.innerHTML="";v.body.removeChild(u).style.display="none"});a=function(u){var F=v.createElement("div");u="on"+u;var N=u in F;if(!N){F.setAttribute(u,"return;");N=typeof F[u]==="function"}return N};
c.support.submitBubbles=a("submit");c.support.changeBubbles=a("change");a=b=d=f=h=null}})();var Ca={},gb=/^(?:\{.*\}|\[.*\])$/;c.extend({cache:{},uuid:0,expando:"jQuery"+c.now(),noData:{embed:true,object:"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000",applet:true},data:function(a,b,d){if(c.acceptData(a)){a=a==P?Ca:a;var e=a.nodeType,f=e?a[c.expando]:null,h=c.cache;if(!(e&&!f&&typeof b==="string"&&d===A)){if(e)f||(a[c.expando]=f=++c.uuid);else h=a;if(typeof b==="object")if(e)h[f]=c.extend(h[f],b);else c.extend(h,
b);else if(e&&!h[f])h[f]={};a=e?h[f]:h;if(d!==A)a[b]=d;return typeof b==="string"?a[b]:a}}},removeData:function(a,b){if(c.acceptData(a)){a=a==P?Ca:a;var d=a.nodeType,e=d?a[c.expando]:a,f=c.cache,h=d?f[e]:e;if(b){if(h){delete h[b];d&&c.isEmptyObject(h)&&c.removeData(a)}}else if(d&&c.support.deleteExpando)delete a[c.expando];else if(a.removeAttribute)a.removeAttribute(c.expando);else if(d)delete f[e];else for(var l in a)delete a[l]}},acceptData:function(a){if(a.nodeName){var b=c.noData[a.nodeName.toLowerCase()];
if(b)return!(b===true||a.getAttribute("classid")!==b)}return true}});c.fn.extend({data:function(a,b){var d=null;if(typeof a==="undefined"){if(this.length){var e=this[0].attributes,f;d=c.data(this[0]);for(var h=0,l=e.length;h<l;h++){f=e[h].name;if(f.indexOf("data-")===0){f=f.substr(5);xa(this[0],f,d[f])}}}return d}else if(typeof a==="object")return this.each(function(){c.data(this,a)});var k=a.split(".");k[1]=k[1]?"."+k[1]:"";if(b===A){d=this.triggerHandler("getData"+k[1]+"!",[k[0]]);if(d===A&&this.length){d=
c.data(this[0],a);d=xa(this[0],a,d)}return d===A&&k[1]?this.data(k[0]):d}else return this.each(function(){var o=c(this),z=[k[0],b];o.triggerHandler("setData"+k[1]+"!",z);c.data(this,a,b);o.triggerHandler("changeData"+k[1]+"!",z)})},removeData:function(a){return this.each(function(){c.removeData(this,a)})}});c.extend({queue:function(a,b,d){if(a){b=(b||"fx")+"queue";var e=c.data(a,b);if(!d)return e||[];if(!e||c.isArray(d))e=c.data(a,b,c.makeArray(d));else e.push(d);return e}},dequeue:function(a,b){b=
b||"fx";var d=c.queue(a,b),e=d.shift();if(e==="inprogress")e=d.shift();if(e){b==="fx"&&d.unshift("inprogress");e.call(a,function(){c.dequeue(a,b)})}}});c.fn.extend({queue:function(a,b){if(typeof a!=="string"){b=a;a="fx"}if(b===A)return c.queue(this[0],a);return this.each(function(){var d=c.queue(this,a,b);a==="fx"&&d[0]!=="inprogress"&&c.dequeue(this,a)})},dequeue:function(a){return this.each(function(){c.dequeue(this,a)})},delay:function(a,b){a=c.fx?c.fx.speeds[a]||a:a;b=b||"fx";return this.queue(b,
function(){var d=this;setTimeout(function(){c.dequeue(d,b)},a)})},clearQueue:function(a){return this.queue(a||"fx",[])}});var ab=/[\n\t]/g,H=/\s+/,sa=/\r/g,Ya=/^(?:href|src|style)$/,ea=/^(?:button|input)$/i,Fa=/^(?:button|input|object|select|textarea)$/i,Ra=/^a(?:rea)?$/i,Ia=/^(?:radio|checkbox)$/i;c.props={"for":"htmlFor","class":"className",readonly:"readOnly",maxlength:"maxLength",cellspacing:"cellSpacing",rowspan:"rowSpan",colspan:"colSpan",tabindex:"tabIndex",usemap:"useMap",frameborder:"frameBorder"};
c.fn.extend({attr:function(a,b){return c.access(this,a,b,true,c.attr)},removeAttr:function(a){return this.each(function(){c.attr(this,a,"");this.nodeType===1&&this.removeAttribute(a)})},addClass:function(a){if(c.isFunction(a))return this.each(function(z){var u=c(this);u.addClass(a.call(this,z,u.attr("class")))});if(a&&typeof a==="string")for(var b=(a||"").split(H),d=0,e=this.length;d<e;d++){var f=this[d];if(f.nodeType===1)if(f.className){for(var h=" "+f.className+" ",l=f.className,k=0,o=b.length;k<
o;k++)if(h.indexOf(" "+b[k]+" ")<0)l+=" "+b[k];f.className=c.trim(l)}else f.className=a}return this},removeClass:function(a){if(c.isFunction(a))return this.each(function(o){var z=c(this);z.removeClass(a.call(this,o,z.attr("class")))});if(a&&typeof a==="string"||a===A)for(var b=(a||"").split(H),d=0,e=this.length;d<e;d++){var f=this[d];if(f.nodeType===1&&f.className)if(a){for(var h=(" "+f.className+" ").replace(ab," "),l=0,k=b.length;l<k;l++)h=h.replace(" "+b[l]+" "," ");f.className=c.trim(h)}else f.className=
""}return this},toggleClass:function(a,b){var d=typeof a,e=typeof b==="boolean";if(c.isFunction(a))return this.each(function(f){var h=c(this);h.toggleClass(a.call(this,f,h.attr("class"),b),b)});return this.each(function(){if(d==="string")for(var f,h=0,l=c(this),k=b,o=a.split(H);f=o[h++];){k=e?k:!l.hasClass(f);l[k?"addClass":"removeClass"](f)}else if(d==="undefined"||d==="boolean"){this.className&&c.data(this,"__className__",this.className);this.className=this.className||a===false?"":c.data(this,"__className__")||
""}})},hasClass:function(a){a=" "+a+" ";for(var b=0,d=this.length;b<d;b++)if((" "+this[b].className+" ").replace(ab," ").indexOf(a)>-1)return true;return false},val:function(a){if(!arguments.length){var b=this[0];if(b){if(c.nodeName(b,"option")){var d=b.attributes.value;return!d||d.specified?b.value:b.text}if(c.nodeName(b,"select")){var e=b.selectedIndex;d=[];var f=b.options;b=b.type==="select-one";if(e<0)return null;var h=b?e:0;for(e=b?e+1:f.length;h<e;h++){var l=f[h];if(l.selected&&(c.support.optDisabled?
!l.disabled:l.getAttribute("disabled")===null)&&(!l.parentNode.disabled||!c.nodeName(l.parentNode,"optgroup"))){a=c(l).val();if(b)return a;d.push(a)}}return d}if(Ia.test(b.type)&&!c.support.checkOn)return b.getAttribute("value")===null?"on":b.value;return(b.value||"").replace(sa,"")}return A}var k=c.isFunction(a);return this.each(function(o){var z=c(this),u=a;if(this.nodeType===1){if(k)u=a.call(this,o,z.val());if(u==null)u="";else if(typeof u==="number")u+="";else if(c.isArray(u))u=c.map(u,function(N){return N==
null?"":N+""});if(c.isArray(u)&&Ia.test(this.type))this.checked=c.inArray(z.val(),u)>=0;else if(c.nodeName(this,"select")){var F=c.makeArray(u);c("option",this).each(function(){this.selected=c.inArray(c(this).val(),F)>=0});if(!F.length)this.selectedIndex=-1}else this.value=u}})}});c.extend({attrFn:{val:true,css:true,html:true,text:true,data:true,width:true,height:true,offset:true},attr:function(a,b,d,e){if(!a||a.nodeType===3||a.nodeType===8)return A;if(e&&b in c.attrFn)return c(a)[b](d);e=a.nodeType!==
1||!c.isXMLDoc(a);var f=d!==A;b=e&&c.props[b]||b;var h=Ya.test(b);if((b in a||a[b]!==A)&&e&&!h){if(f){b==="type"&&ea.test(a.nodeName)&&a.parentNode&&c.error("type property can't be changed");if(d===null)a.nodeType===1&&a.removeAttribute(b);else a[b]=d}if(c.nodeName(a,"form")&&a.getAttributeNode(b))return a.getAttributeNode(b).nodeValue;if(b==="tabIndex")return(b=a.getAttributeNode("tabIndex"))&&b.specified?b.value:Fa.test(a.nodeName)||Ra.test(a.nodeName)&&a.href?0:A;return a[b]}if(!c.support.style&&
e&&b==="style"){if(f)a.style.cssText=""+d;return a.style.cssText}f&&a.setAttribute(b,""+d);if(!a.attributes[b]&&a.hasAttribute&&!a.hasAttribute(b))return A;a=!c.support.hrefNormalized&&e&&h?a.getAttribute(b,2):a.getAttribute(b);return a===null?A:a}});var Ma=/\.(.*)$/,ta=/^(?:textarea|input|select)$/i,hb=/\./g,Sa=/ /g,Ea=/[^\w\s.|`]/g,Za=function(a){return a.replace(Ea,"\\$&")},$a={focusin:0,focusout:0};c.event={add:function(a,b,d,e){if(!(a.nodeType===3||a.nodeType===8)){if(c.isWindow(a)&&a!==P&&!a.frameElement)a=
P;if(d===false)d=Z;else if(!d)return;var f,h;if(d.handler){f=d;d=f.handler}if(!d.guid)d.guid=c.guid++;if(h=c.data(a)){var l=a.nodeType?"events":"__events__",k=h[l],o=h.handle;if(typeof k==="function"){o=k.handle;k=k.events}else if(!k){a.nodeType||(h[l]=h=function(){});h.events=k={}}if(!o)h.handle=o=function(){return typeof c!=="undefined"&&!c.event.triggered?c.event.handle.apply(o.elem,arguments):A};o.elem=a;b=b.split(" ");for(var z=0,u;l=b[z++];){h=f?c.extend({},f):{handler:d,data:e};if(l.indexOf(".")>
-1){u=l.split(".");l=u.shift();h.namespace=u.slice(0).sort().join(".")}else{u=[];h.namespace=""}h.type=l;if(!h.guid)h.guid=d.guid;var F=k[l],N=c.event.special[l]||{};if(!F){F=k[l]=[];if(!N.setup||N.setup.call(a,e,u,o)===false)if(a.addEventListener)a.addEventListener(l,o,false);else a.attachEvent&&a.attachEvent("on"+l,o)}if(N.add){N.add.call(a,h);if(!h.handler.guid)h.handler.guid=d.guid}F.push(h);c.event.global[l]=true}a=null}}},global:{},remove:function(a,b,d,e){if(!(a.nodeType===3||a.nodeType===
8)){if(d===false)d=Z;var f,h,l=0,k,o,z,u,F,N,ga=a.nodeType?"events":"__events__",B=c.data(a),fa=B&&B[ga];if(B&&fa){if(typeof fa==="function"){B=fa;fa=fa.events}if(b&&b.type){d=b.handler;b=b.type}if(!b||typeof b==="string"&&b.charAt(0)==="."){b=b||"";for(f in fa)c.event.remove(a,f+b)}else{for(b=b.split(" ");f=b[l++];){u=f;k=f.indexOf(".")<0;o=[];if(!k){o=f.split(".");f=o.shift();z=new RegExp("(^|\\.)"+c.map(o.slice(0).sort(),Za).join("\\.(?:.*\\.)?")+"(\\.|$)")}if(F=fa[f])if(d){u=c.event.special[f]||
{};for(h=e||0;h<F.length;h++){N=F[h];if(d.guid===N.guid){if(k||z.test(N.namespace)){e==null&&F.splice(h--,1);u.remove&&u.remove.call(a,N)}if(e!=null)break}}if(F.length===0||e!=null&&F.length===1){if(!u.teardown||u.teardown.call(a,o)===false)c.removeEvent(a,f,B.handle);delete fa[f]}}else for(h=0;h<F.length;h++){N=F[h];if(k||z.test(N.namespace)){c.event.remove(a,u,N.handler,h);F.splice(h--,1)}}}if(c.isEmptyObject(fa)){if(b=B.handle)b.elem=null;delete B.events;delete B.handle;if(typeof B==="function")c.removeData(a,
ga);else c.isEmptyObject(B)&&c.removeData(a)}}}}},trigger:function(a,b,d,e){var f=a.type||a;if(!e){a=typeof a==="object"?a[c.expando]?a:c.extend(c.Event(f),a):c.Event(f);if(f.indexOf("!")>=0){a.type=f=f.slice(0,-1);a.exclusive=true}if(!d){a.stopPropagation();c.event.global[f]&&c.each(c.cache,function(){this.events&&this.events[f]&&c.event.trigger(a,b,this.handle.elem)})}if(!d||d.nodeType===3||d.nodeType===8)return A;a.result=A;a.target=d;b=c.makeArray(b);b.unshift(a)}a.currentTarget=d;(e=d.nodeType?
c.data(d,"handle"):(c.data(d,"__events__")||{}).handle)&&e.apply(d,b);e=d.parentNode||d.ownerDocument;try{if(!(d&&d.nodeName&&c.noData[d.nodeName.toLowerCase()]))if(d["on"+f]&&d["on"+f].apply(d,b)===false){a.result=false;a.preventDefault()}}catch(h){}if(!a.isPropagationStopped()&&e)c.event.trigger(a,b,e,true);else if(!a.isDefaultPrevented()){var l;e=a.target;var k=f.replace(Ma,""),o=c.nodeName(e,"a")&&k==="click",z=c.event.special[k]||{};if((!z._default||z._default.call(d,a)===false)&&!o&&!(e&&e.nodeName&&
c.noData[e.nodeName.toLowerCase()])){try{if(e[k]){if(l=e["on"+k])e["on"+k]=null;c.event.triggered=true;e[k]()}}catch(u){}if(l)e["on"+k]=l;c.event.triggered=false}}},handle:function(a){var b,d,e,f;d=[];var h=c.makeArray(arguments);a=h[0]=c.event.fix(a||P.event);a.currentTarget=this;b=a.type.indexOf(".")<0&&!a.exclusive;if(!b){e=a.type.split(".");a.type=e.shift();d=e.slice(0).sort();e=new RegExp("(^|\\.)"+d.join("\\.(?:.*\\.)?")+"(\\.|$)")}a.namespace=a.namespace||d.join(".");f=c.data(this,this.nodeType?
"events":"__events__");if(typeof f==="function")f=f.events;d=(f||{})[a.type];if(f&&d){d=d.slice(0);f=0;for(var l=d.length;f<l;f++){var k=d[f];if(b||e.test(k.namespace)){a.handler=k.handler;a.data=k.data;a.handleObj=k;k=k.handler.apply(this,h);if(k!==A){a.result=k;if(k===false){a.preventDefault();a.stopPropagation()}}if(a.isImmediatePropagationStopped())break}}}return a.result},props:"altKey attrChange attrName bubbles button cancelable charCode clientX clientY ctrlKey currentTarget data detail eventPhase fromElement handler keyCode layerX layerY metaKey newValue offsetX offsetY pageX pageY prevValue relatedNode relatedTarget screenX screenY shiftKey srcElement target toElement view wheelDelta which".split(" "),
fix:function(a){if(a[c.expando])return a;var b=a;a=c.Event(b);for(var d=this.props.length,e;d;){e=this.props[--d];a[e]=b[e]}if(!a.target)a.target=a.srcElement||v;if(a.target.nodeType===3)a.target=a.target.parentNode;if(!a.relatedTarget&&a.fromElement)a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;if(a.pageX==null&&a.clientX!=null){b=v.documentElement;d=v.body;a.pageX=a.clientX+(b&&b.scrollLeft||d&&d.scrollLeft||0)-(b&&b.clientLeft||d&&d.clientLeft||0);a.pageY=a.clientY+(b&&b.scrollTop||
d&&d.scrollTop||0)-(b&&b.clientTop||d&&d.clientTop||0)}if(a.which==null&&(a.charCode!=null||a.keyCode!=null))a.which=a.charCode!=null?a.charCode:a.keyCode;if(!a.metaKey&&a.ctrlKey)a.metaKey=a.ctrlKey;if(!a.which&&a.button!==A)a.which=a.button&1?1:a.button&2?3:a.button&4?2:0;return a},guid:1E8,proxy:c.proxy,special:{ready:{setup:c.bindReady,teardown:c.noop},live:{add:function(a){c.event.add(this,T(a.origType,a.selector),c.extend({},a,{handler:L,guid:a.handler.guid}))},remove:function(a){c.event.remove(this,
T(a.origType,a.selector),a)}},beforeunload:{setup:function(a,b,d){if(c.isWindow(this))this.onbeforeunload=d},teardown:function(a,b){if(this.onbeforeunload===b)this.onbeforeunload=null}}}};c.removeEvent=v.removeEventListener?function(a,b,d){a.removeEventListener&&a.removeEventListener(b,d,false)}:function(a,b,d){a.detachEvent&&a.detachEvent("on"+b,d)};c.Event=function(a){if(!this.preventDefault)return new c.Event(a);if(a&&a.type){this.originalEvent=a;this.type=a.type}else this.type=a;this.timeStamp=
c.now();this[c.expando]=true};c.Event.prototype={preventDefault:function(){this.isDefaultPrevented=J;var a=this.originalEvent;if(a)if(a.preventDefault)a.preventDefault();else a.returnValue=false},stopPropagation:function(){this.isPropagationStopped=J;var a=this.originalEvent;if(a){a.stopPropagation&&a.stopPropagation();a.cancelBubble=true}},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=J;this.stopPropagation()},isDefaultPrevented:Z,isPropagationStopped:Z,isImmediatePropagationStopped:Z};
var x=function(a){var b=a.relatedTarget;try{for(;b&&b!==this;)b=b.parentNode;if(b!==this){a.type=a.data;c.event.handle.apply(this,arguments)}}catch(d){}},C=function(a){a.type=a.data;c.event.handle.apply(this,arguments)};c.each({mouseenter:"mouseover",mouseleave:"mouseout"},function(a,b){c.event.special[a]={setup:function(d){c.event.add(this,b,d&&d.selector?C:x,a)},teardown:function(d){c.event.remove(this,b,d&&d.selector?C:x)}}});if(!c.support.submitBubbles)c.event.special.submit={setup:function(){if(this.nodeName.toLowerCase()!==
"form"){c.event.add(this,"click.specialSubmit",function(a){var b=a.target,d=b.type;if((d==="submit"||d==="image")&&c(b).closest("form").length){a.liveFired=A;return W("submit",this,arguments)}});c.event.add(this,"keypress.specialSubmit",function(a){var b=a.target,d=b.type;if((d==="text"||d==="password")&&c(b).closest("form").length&&a.keyCode===13){a.liveFired=A;return W("submit",this,arguments)}})}else return false},teardown:function(){c.event.remove(this,".specialSubmit")}};if(!c.support.changeBubbles){var K,
Q=function(a){var b=a.type,d=a.value;if(b==="radio"||b==="checkbox")d=a.checked;else if(b==="select-multiple")d=a.selectedIndex>-1?c.map(a.options,function(e){return e.selected}).join("-"):"";else if(a.nodeName.toLowerCase()==="select")d=a.selectedIndex;return d},$=function(a,b){var d=a.target,e,f;if(!(!ta.test(d.nodeName)||d.readOnly)){e=c.data(d,"_change_data");f=Q(d);if(a.type!=="focusout"||d.type!=="radio")c.data(d,"_change_data",f);if(!(e===A||f===e))if(e!=null||f){a.type="change";a.liveFired=
A;return c.event.trigger(a,b,d)}}};c.event.special.change={filters:{focusout:$,beforedeactivate:$,click:function(a){var b=a.target,d=b.type;if(d==="radio"||d==="checkbox"||b.nodeName.toLowerCase()==="select")return $.call(this,a)},keydown:function(a){var b=a.target,d=b.type;if(a.keyCode===13&&b.nodeName.toLowerCase()!=="textarea"||a.keyCode===32&&(d==="checkbox"||d==="radio")||d==="select-multiple")return $.call(this,a)},beforeactivate:function(a){a=a.target;c.data(a,"_change_data",Q(a))}},setup:function(){if(this.type===
"file")return false;for(var a in K)c.event.add(this,a+".specialChange",K[a]);return ta.test(this.nodeName)},teardown:function(){c.event.remove(this,".specialChange");return ta.test(this.nodeName)}};K=c.event.special.change.filters;K.focus=K.beforeactivate}v.addEventListener&&c.each({focus:"focusin",blur:"focusout"},function(a,b){function d(e){e=c.event.fix(e);e.type=b;return c.event.trigger(e,null,e.target)}c.event.special[b]={setup:function(){$a[b]++===0&&v.addEventListener(a,d,true)},teardown:function(){--$a[b]===
0&&v.removeEventListener(a,d,true)}}});c.each(["bind","one"],function(a,b){c.fn[b]=function(d,e,f){if(typeof d==="object"){for(var h in d)this[b](h,e,d[h],f);return this}if(c.isFunction(e)||e===false){f=e;e=A}var l=b==="one"?c.proxy(f,function(o){c(this).unbind(o,l);return f.apply(this,arguments)}):f;if(d==="unload"&&b!=="one")this.one(d,e,f);else{h=0;for(var k=this.length;h<k;h++)c.event.add(this[h],d,l,e)}return this}});c.fn.extend({unbind:function(a,b){if(typeof a==="object"&&!a.preventDefault)for(var d in a)this.unbind(d,
a[d]);else{d=0;for(var e=this.length;d<e;d++)c.event.remove(this[d],a,b)}return this},delegate:function(a,b,d,e){return this.live(b,d,e,a)},undelegate:function(a,b,d){return arguments.length===0?this.unbind("live"):this.die(b,null,d,a)},trigger:function(a,b){return this.each(function(){c.event.trigger(a,b,this)})},triggerHandler:function(a,b){if(this[0]){a=c.Event(a);a.preventDefault();a.stopPropagation();c.event.trigger(a,b,this[0]);return a.result}},toggle:function(a){for(var b=arguments,d=1;d<
b.length;)c.proxy(a,b[d++]);return this.click(c.proxy(a,function(e){var f=(c.data(this,"lastToggle"+a.guid)||0)%d;c.data(this,"lastToggle"+a.guid,f+1);e.preventDefault();return b[f].apply(this,arguments)||false}))},hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});var R={focus:"focusin",blur:"focusout",mouseenter:"mouseover",mouseleave:"mouseout"};c.each(["live","die"],function(a,b){c.fn[b]=function(d,e,f,h){var l,k=0,o,z,u=h||this.selector;h=h?this:c(this.context);if(typeof d==="object"&&
!d.preventDefault){for(l in d)h[b](l,e,d[l],u);return this}if(c.isFunction(e)){f=e;e=A}for(d=(d||"").split(" ");(l=d[k++])!=null;){o=Ma.exec(l);z="";if(o){z=o[0];l=l.replace(Ma,"")}if(l==="hover")d.push("mouseenter"+z,"mouseleave"+z);else{o=l;if(l==="focus"||l==="blur"){d.push(R[l]+z);l+=z}else l=(R[l]||l)+z;if(b==="live"){z=0;for(var F=h.length;z<F;z++)c.event.add(h[z],"live."+T(l,u),{data:e,selector:u,handler:f,origType:l,origHandler:f,preType:o})}else h.unbind("live."+T(l,u),f)}}return this}});
c.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error".split(" "),function(a,b){c.fn[b]=function(d,e){if(e==null){e=d;d=null}return arguments.length>0?this.bind(b,d,e):this.trigger(b)};if(c.attrFn)c.attrFn[b]=true});P.attachEvent&&!P.addEventListener&&c(P).bind("unload",function(){for(var a in c.cache)if(c.cache[a].handle)try{c.event.remove(c.cache[a].handle.elem)}catch(b){}});
(function(){function a(g,i,n,p,r,t){r=0;for(var E=p.length;r<E;r++){var G=p[r];if(G){var X=false;for(G=G[g];G;){if(G.sizcache===n){X=p[G.sizset];break}if(G.nodeType===1&&!t){G.sizcache=n;G.sizset=r}if(G.nodeName.toLowerCase()===i){X=G;break}G=G[g]}p[r]=X}}}function b(g,i,n,p,r,t){r=0;for(var E=p.length;r<E;r++){var G=p[r];if(G){var X=false;for(G=G[g];G;){if(G.sizcache===n){X=p[G.sizset];break}if(G.nodeType===1){if(!t){G.sizcache=n;G.sizset=r}if(typeof i!=="string"){if(G===i){X=true;break}}else if(k.filter(i,
[G]).length>0){X=G;break}}G=G[g]}p[r]=X}}}var d=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^\[\]]*\]|['"][^'"]*['"]|[^\[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,e=0,f=Object.prototype.toString,h=false,l=true;[0,0].sort(function(){l=false;return 0});var k=function(g,i,n,p){n=n||[];var r=i=i||v;if(i.nodeType!==1&&i.nodeType!==9)return[];if(!g||typeof g!=="string")return n;var t,E,G,X,ra,va=true,wa=k.isXML(i),U=[],Na=g;do{d.exec("");if(t=d.exec(Na)){Na=t[3];U.push(t[1]);if(t[2]){X=
t[3];break}}}while(t);if(U.length>1&&z.exec(g))if(U.length===2&&o.relative[U[0]])E=ua(U[0]+U[1],i);else for(E=o.relative[U[0]]?[i]:k(U.shift(),i);U.length;){g=U.shift();if(o.relative[g])g+=U.shift();E=ua(g,E)}else{if(!p&&U.length>1&&i.nodeType===9&&!wa&&o.match.ID.test(U[0])&&!o.match.ID.test(U[U.length-1])){t=k.find(U.shift(),i,wa);i=t.expr?k.filter(t.expr,t.set)[0]:t.set[0]}if(i){t=p?{expr:U.pop(),set:N(p)}:k.find(U.pop(),U.length===1&&(U[0]==="~"||U[0]==="+")&&i.parentNode?i.parentNode:i,wa);E=
t.expr?k.filter(t.expr,t.set):t.set;if(U.length>0)G=N(E);else va=false;for(;U.length;){t=ra=U.pop();if(o.relative[ra])t=U.pop();else ra="";if(t==null)t=i;o.relative[ra](G,t,wa)}}else G=[]}G||(G=E);G||k.error(ra||g);if(f.call(G)==="[object Array]")if(va)if(i&&i.nodeType===1)for(g=0;G[g]!=null;g++){if(G[g]&&(G[g]===true||G[g].nodeType===1&&k.contains(i,G[g])))n.push(E[g])}else for(g=0;G[g]!=null;g++)G[g]&&G[g].nodeType===1&&n.push(E[g]);else n.push.apply(n,G);else N(G,n);if(X){k(X,r,n,p);k.uniqueSort(n)}return n};
k.uniqueSort=function(g){if(B){h=l;g.sort(B);if(h)for(var i=1;i<g.length;i++)g[i]===g[i-1]&&g.splice(i--,1)}return g};k.matches=function(g,i){return k(g,null,null,i)};k.matchesSelector=function(g,i){return k(i,null,null,[g]).length>0};k.find=function(g,i,n){var p;if(!g)return[];for(var r=0,t=o.order.length;r<t;r++){var E,G=o.order[r];if(E=o.leftMatch[G].exec(g)){var X=E[1];E.splice(1,1);if(X.substr(X.length-1)!=="\\"){E[1]=(E[1]||"").replace(/\\/g,"");p=o.find[G](E,i,n);if(p!=null){g=g.replace(o.match[G],
"");break}}}}p||(p=i.getElementsByTagName("*"));return{set:p,expr:g}};k.filter=function(g,i,n,p){for(var r,t,E=g,G=[],X=i,ra=i&&i[0]&&k.isXML(i[0]);g&&i.length;){for(var va in o.filter)if((r=o.leftMatch[va].exec(g))!=null&&r[2]){var wa,U,Na=o.filter[va];U=r[1];t=false;r.splice(1,1);if(U.substr(U.length-1)!=="\\"){if(X===G)G=[];if(o.preFilter[va])if(r=o.preFilter[va](r,X,n,G,p,ra)){if(r===true)continue}else t=wa=true;if(r)for(var j=0;(U=X[j])!=null;j++)if(U){wa=Na(U,r,j,X);var s=p^!!wa;if(n&&wa!=null)if(s)t=
true;else X[j]=false;else if(s){G.push(U);t=true}}if(wa!==A){n||(X=G);g=g.replace(o.match[va],"");if(!t)return[];break}}}if(g===E)if(t==null)k.error(g);else break;E=g}return X};k.error=function(g){throw"Syntax error, unrecognized expression: "+g;};var o=k.selectors={order:["ID","NAME","TAG"],match:{ID:/#((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,CLASS:/\.((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,NAME:/\[name=['"]*((?:[\w\u00c0-\uFFFF\-]|\\.)+)['"]*\]/,ATTR:/\[\s*((?:[\w\u00c0-\uFFFF\-]|\\.)+)\s*(?:(\S?=)\s*(['"]*)(.*?)\3|)\s*\]/,
TAG:/^((?:[\w\u00c0-\uFFFF\*\-]|\\.)+)/,CHILD:/:(only|nth|last|first)-child(?:\((even|odd|[\dn+\-]*)\))?/,POS:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^\-]|$)/,PSEUDO:/:((?:[\w\u00c0-\uFFFF\-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},leftMatch:{},attrMap:{"class":"className","for":"htmlFor"},attrHandle:{href:function(g){return g.getAttribute("href")}},relative:{"+":function(g,i){var n=typeof i==="string",p=n&&!/\W/.test(i);n=n&&!p;if(p)i=i.toLowerCase();p=0;for(var r=g.length,
t;p<r;p++)if(t=g[p]){for(;(t=t.previousSibling)&&t.nodeType!==1;);g[p]=n||t&&t.nodeName.toLowerCase()===i?t||false:t===i}n&&k.filter(i,g,true)},">":function(g,i){var n,p=typeof i==="string",r=0,t=g.length;if(p&&!/\W/.test(i))for(i=i.toLowerCase();r<t;r++){if(n=g[r]){n=n.parentNode;g[r]=n.nodeName.toLowerCase()===i?n:false}}else{for(;r<t;r++)if(n=g[r])g[r]=p?n.parentNode:n.parentNode===i;p&&k.filter(i,g,true)}},"":function(g,i,n){var p,r=e++,t=b;if(typeof i==="string"&&!/\W/.test(i)){p=i=i.toLowerCase();
t=a}t("parentNode",i,r,g,p,n)},"~":function(g,i,n){var p,r=e++,t=b;if(typeof i==="string"&&!/\W/.test(i)){p=i=i.toLowerCase();t=a}t("previousSibling",i,r,g,p,n)}},find:{ID:function(g,i,n){if(typeof i.getElementById!=="undefined"&&!n)return(g=i.getElementById(g[1]))&&g.parentNode?[g]:[]},NAME:function(g,i){if(typeof i.getElementsByName!=="undefined"){var n=[];i=i.getElementsByName(g[1]);for(var p=0,r=i.length;p<r;p++)i[p].getAttribute("name")===g[1]&&n.push(i[p]);return n.length===0?null:n}},TAG:function(g,
i){return i.getElementsByTagName(g[1])}},preFilter:{CLASS:function(g,i,n,p,r,t){g=" "+g[1].replace(/\\/g,"")+" ";if(t)return g;t=0;for(var E;(E=i[t])!=null;t++)if(E)if(r^(E.className&&(" "+E.className+" ").replace(/[\t\n]/g," ").indexOf(g)>=0))n||p.push(E);else if(n)i[t]=false;return false},ID:function(g){return g[1].replace(/\\/g,"")},TAG:function(g){return g[1].toLowerCase()},CHILD:function(g){if(g[1]==="nth"){var i=/(-?)(\d*)n((?:\+|-)?\d*)/.exec(g[2]==="even"&&"2n"||g[2]==="odd"&&"2n+1"||!/\D/.test(g[2])&&
"0n+"+g[2]||g[2]);g[2]=i[1]+(i[2]||1)-0;g[3]=i[3]-0}g[0]=e++;return g},ATTR:function(g,i,n,p,r,t){i=g[1].replace(/\\/g,"");if(!t&&o.attrMap[i])g[1]=o.attrMap[i];if(g[2]==="~=")g[4]=" "+g[4]+" ";return g},PSEUDO:function(g,i,n,p,r){if(g[1]==="not")if((d.exec(g[3])||"").length>1||/^\w/.test(g[3]))g[3]=k(g[3],null,null,i);else{g=k.filter(g[3],i,n,true^r);n||p.push.apply(p,g);return false}else if(o.match.POS.test(g[0])||o.match.CHILD.test(g[0]))return true;return g},POS:function(g){g.unshift(true);return g}},
filters:{enabled:function(g){return g.disabled===false&&g.type!=="hidden"},disabled:function(g){return g.disabled===true},checked:function(g){return g.checked===true},selected:function(g){return g.selected===true},parent:function(g){return!!g.firstChild},empty:function(g){return!g.firstChild},has:function(g,i,n){return!!k(n[3],g).length},header:function(g){return/h\d/i.test(g.nodeName)},text:function(g){return"text"===g.type},radio:function(g){return"radio"===g.type},checkbox:function(g){return"checkbox"===
g.type},file:function(g){return"file"===g.type},password:function(g){return"password"===g.type},submit:function(g){return"submit"===g.type},image:function(g){return"image"===g.type},reset:function(g){return"reset"===g.type},button:function(g){return"button"===g.type||g.nodeName.toLowerCase()==="button"},input:function(g){return/input|select|textarea|button/i.test(g.nodeName)}},setFilters:{first:function(g,i){return i===0},last:function(g,i,n,p){return i===p.length-1},even:function(g,i){return i%2===
0},odd:function(g,i){return i%2===1},lt:function(g,i,n){return i<n[3]-0},gt:function(g,i,n){return i>n[3]-0},nth:function(g,i,n){return n[3]-0===i},eq:function(g,i,n){return n[3]-0===i}},filter:{PSEUDO:function(g,i,n,p){var r=i[1],t=o.filters[r];if(t)return t(g,n,i,p);else if(r==="contains")return(g.textContent||g.innerText||k.getText([g])||"").indexOf(i[3])>=0;else if(r==="not"){i=i[3];n=0;for(p=i.length;n<p;n++)if(i[n]===g)return false;return true}else k.error("Syntax error, unrecognized expression: "+
r)},CHILD:function(g,i){var n=i[1],p=g;switch(n){case "only":case "first":for(;p=p.previousSibling;)if(p.nodeType===1)return false;if(n==="first")return true;p=g;case "last":for(;p=p.nextSibling;)if(p.nodeType===1)return false;return true;case "nth":n=i[2];var r=i[3];if(n===1&&r===0)return true;i=i[0];var t=g.parentNode;if(t&&(t.sizcache!==i||!g.nodeIndex)){var E=0;for(p=t.firstChild;p;p=p.nextSibling)if(p.nodeType===1)p.nodeIndex=++E;t.sizcache=i}g=g.nodeIndex-r;return n===0?g===0:g%n===0&&g/n>=
0}},ID:function(g,i){return g.nodeType===1&&g.getAttribute("id")===i},TAG:function(g,i){return i==="*"&&g.nodeType===1||g.nodeName.toLowerCase()===i},CLASS:function(g,i){return(" "+(g.className||g.getAttribute("class"))+" ").indexOf(i)>-1},ATTR:function(g,i){var n=i[1];g=o.attrHandle[n]?o.attrHandle[n](g):g[n]!=null?g[n]:g.getAttribute(n);n=g+"";var p=i[2];i=i[4];return g==null?p==="!=":p==="="?n===i:p==="*="?n.indexOf(i)>=0:p==="~="?(" "+n+" ").indexOf(i)>=0:!i?n&&g!==false:p==="!="?n!==i:p==="^="?
n.indexOf(i)===0:p==="$="?n.substr(n.length-i.length)===i:p==="|="?n===i||n.substr(0,i.length+1)===i+"-":false},POS:function(g,i,n,p){var r=o.setFilters[i[2]];if(r)return r(g,n,i,p)}}},z=o.match.POS,u=function(g,i){return"\\"+(i-0+1)};for(var F in o.match){o.match[F]=new RegExp(o.match[F].source+/(?![^\[]*\])(?![^\(]*\))/.source);o.leftMatch[F]=new RegExp(/(^(?:.|\r|\n)*?)/.source+o.match[F].source.replace(/\\(\d+)/g,u))}var N=function(g,i){g=Array.prototype.slice.call(g,0);if(i){i.push.apply(i,g);
return i}return g};try{Array.prototype.slice.call(v.documentElement.childNodes,0)}catch(ga){N=function(g,i){var n=0;i=i||[];if(f.call(g)==="[object Array]")Array.prototype.push.apply(i,g);else if(typeof g.length==="number")for(var p=g.length;n<p;n++)i.push(g[n]);else for(;g[n];n++)i.push(g[n]);return i}}var B,fa;if(v.documentElement.compareDocumentPosition)B=function(g,i){if(g===i){h=true;return 0}if(!g.compareDocumentPosition||!i.compareDocumentPosition)return g.compareDocumentPosition?-1:1;return g.compareDocumentPosition(i)&
4?-1:1};else{B=function(g,i){var n,p,r=[],t=[];n=g.parentNode;p=i.parentNode;var E=n;if(g===i){h=true;return 0}else if(n===p)return fa(g,i);else if(n){if(!p)return 1}else return-1;for(;E;){r.unshift(E);E=E.parentNode}for(E=p;E;){t.unshift(E);E=E.parentNode}n=r.length;p=t.length;for(E=0;E<n&&E<p;E++)if(r[E]!==t[E])return fa(r[E],t[E]);return E===n?fa(g,t[E],-1):fa(r[E],i,1)};fa=function(g,i,n){if(g===i)return n;for(g=g.nextSibling;g;){if(g===i)return-1;g=g.nextSibling}return 1}}k.getText=function(g){for(var i=
"",n,p=0;g[p];p++){n=g[p];if(n.nodeType===3||n.nodeType===4)i+=n.nodeValue;else if(n.nodeType!==8)i+=k.getText(n.childNodes)}return i};(function(){var g=v.createElement("div"),i="script"+(new Date).getTime(),n=v.documentElement;g.innerHTML="<a name='"+i+"'/>";n.insertBefore(g,n.firstChild);if(v.getElementById(i)){o.find.ID=function(p,r,t){if(typeof r.getElementById!=="undefined"&&!t)return(r=r.getElementById(p[1]))?r.id===p[1]||typeof r.getAttributeNode!=="undefined"&&r.getAttributeNode("id").nodeValue===
p[1]?[r]:A:[]};o.filter.ID=function(p,r){var t=typeof p.getAttributeNode!=="undefined"&&p.getAttributeNode("id");return p.nodeType===1&&t&&t.nodeValue===r}}n.removeChild(g);n=g=null})();(function(){var g=v.createElement("div");g.appendChild(v.createComment(""));if(g.getElementsByTagName("*").length>0)o.find.TAG=function(i,n){n=n.getElementsByTagName(i[1]);if(i[1]==="*"){i=[];for(var p=0;n[p];p++)n[p].nodeType===1&&i.push(n[p]);n=i}return n};g.innerHTML="<a href='#'></a>";if(g.firstChild&&typeof g.firstChild.getAttribute!==
"undefined"&&g.firstChild.getAttribute("href")!=="#")o.attrHandle.href=function(i){return i.getAttribute("href",2)};g=null})();v.querySelectorAll&&function(){var g=k,i=v.createElement("div");i.innerHTML="<p class='TEST'></p>";if(!(i.querySelectorAll&&i.querySelectorAll(".TEST").length===0)){k=function(p,r,t,E){r=r||v;p=p.replace(/\=\s*([^'"\]]*)\s*\]/g,"='$1']");if(!E&&!k.isXML(r))if(r.nodeType===9)try{return N(r.querySelectorAll(p),t)}catch(G){}else if(r.nodeType===1&&r.nodeName.toLowerCase()!==
"object"){var X=r.getAttribute("id"),ra=X||"__sizzle__";X||r.setAttribute("id",ra);try{return N(r.querySelectorAll("#"+ra+" "+p),t)}catch(va){}finally{X||r.removeAttribute("id")}}return g(p,r,t,E)};for(var n in g)k[n]=g[n];i=null}}();(function(){var g=v.documentElement,i=g.matchesSelector||g.mozMatchesSelector||g.webkitMatchesSelector||g.msMatchesSelector,n=false;try{i.call(v.documentElement,"[test!='']:sizzle")}catch(p){n=true}if(i)k.matchesSelector=function(r,t){t=t.replace(/\=\s*([^'"\]]*)\s*\]/g,
"='$1']");if(!k.isXML(r))try{if(n||!o.match.PSEUDO.test(t)&&!/!=/.test(t))return i.call(r,t)}catch(E){}return k(t,null,null,[r]).length>0}})();(function(){var g=v.createElement("div");g.innerHTML="<div class='test e'></div><div class='test'></div>";if(!(!g.getElementsByClassName||g.getElementsByClassName("e").length===0)){g.lastChild.className="e";if(g.getElementsByClassName("e").length!==1){o.order.splice(1,0,"CLASS");o.find.CLASS=function(i,n,p){if(typeof n.getElementsByClassName!=="undefined"&&
!p)return n.getElementsByClassName(i[1])};g=null}}})();k.contains=v.documentElement.contains?function(g,i){return g!==i&&(g.contains?g.contains(i):true)}:v.documentElement.compareDocumentPosition?function(g,i){return!!(g.compareDocumentPosition(i)&16)}:function(){return false};k.isXML=function(g){return(g=(g?g.ownerDocument||g:0).documentElement)?g.nodeName!=="HTML":false};var ua=function(g,i){var n,p=[],r="";for(i=i.nodeType?[i]:i;n=o.match.PSEUDO.exec(g);){r+=n[0];g=g.replace(o.match.PSEUDO,"")}g=
o.relative[g]?g+"*":g;n=0;for(var t=i.length;n<t;n++)k(g,i[n],p);return k.filter(r,p)};c.find=k;c.expr=k.selectors;c.expr[":"]=c.expr.filters;c.unique=k.uniqueSort;c.text=k.getText;c.isXMLDoc=k.isXML;c.contains=k.contains})();var Oa=/Until$/,bb=/^(?:parents|prevUntil|prevAll)/,cb=/,/,Ua=/^.[^:#\[\.,]*$/,db=Array.prototype.slice,Pa=c.expr.match.POS;c.fn.extend({find:function(a){for(var b=this.pushStack("","find",a),d=0,e=0,f=this.length;e<f;e++){d=b.length;c.find(a,this[e],b);if(e>0)for(var h=d;h<
b.length;h++)for(var l=0;l<d;l++)if(b[l]===b[h]){b.splice(h--,1);break}}return b},has:function(a){var b=c(a);return this.filter(function(){for(var d=0,e=b.length;d<e;d++)if(c.contains(this,b[d]))return true})},not:function(a){return this.pushStack(ja(this,a,false),"not",a)},filter:function(a){return this.pushStack(ja(this,a,true),"filter",a)},is:function(a){return!!a&&c.filter(a,this).length>0},closest:function(a,b){var d=[],e,f,h=this[0];if(c.isArray(a)){var l,k={},o=1;if(h&&a.length){e=0;for(f=
a.length;e<f;e++){l=a[e];k[l]||(k[l]=c.expr.match.POS.test(l)?c(l,b||this.context):l)}for(;h&&h.ownerDocument&&h!==b;){for(l in k){a=k[l];if(a.jquery?a.index(h)>-1:c(h).is(a))d.push({selector:l,elem:h,level:o})}h=h.parentNode;o++}}return d}l=Pa.test(a)?c(a,b||this.context):null;e=0;for(f=this.length;e<f;e++)for(h=this[e];h;)if(l?l.index(h)>-1:c.find.matchesSelector(h,a)){d.push(h);break}else{h=h.parentNode;if(!h||!h.ownerDocument||h===b)break}d=d.length>1?c.unique(d):d;return this.pushStack(d,"closest",
a)},index:function(a){if(!a||typeof a==="string")return c.inArray(this[0],a?c(a):this.parent().children());return c.inArray(a.jquery?a[0]:a,this)},add:function(a,b){a=typeof a==="string"?c(a,b||this.context):c.makeArray(a);b=c.merge(this.get(),a);return this.pushStack(S(a[0])||S(b[0])?b:c.unique(b))},andSelf:function(){return this.add(this.prevObject)}});c.each({parent:function(a){return(a=a.parentNode)&&a.nodeType!==11?a:null},parents:function(a){return c.dir(a,"parentNode")},parentsUntil:function(a,
b,d){return c.dir(a,"parentNode",d)},next:function(a){return c.nth(a,2,"nextSibling")},prev:function(a){return c.nth(a,2,"previousSibling")},nextAll:function(a){return c.dir(a,"nextSibling")},prevAll:function(a){return c.dir(a,"previousSibling")},nextUntil:function(a,b,d){return c.dir(a,"nextSibling",d)},prevUntil:function(a,b,d){return c.dir(a,"previousSibling",d)},siblings:function(a){return c.sibling(a.parentNode.firstChild,a)},children:function(a){return c.sibling(a.firstChild)},contents:function(a){return c.nodeName(a,
"iframe")?a.contentDocument||a.contentWindow.document:c.makeArray(a.childNodes)}},function(a,b){c.fn[a]=function(d,e){var f=c.map(this,b,d);Oa.test(a)||(e=d);if(e&&typeof e==="string")f=c.filter(e,f);f=this.length>1?c.unique(f):f;if((this.length>1||cb.test(e))&&bb.test(a))f=f.reverse();return this.pushStack(f,a,db.call(arguments).join(","))}});c.extend({filter:function(a,b,d){if(d)a=":not("+a+")";return b.length===1?c.find.matchesSelector(b[0],a)?[b[0]]:[]:c.find.matches(a,b)},dir:function(a,b,d){var e=
[];for(a=a[b];a&&a.nodeType!==9&&(d===A||a.nodeType!==1||!c(a).is(d));){a.nodeType===1&&e.push(a);a=a[b]}return e},nth:function(a,b,d){b=b||1;for(var e=0;a;a=a[d])if(a.nodeType===1&&++e===b)break;return a},sibling:function(a,b){for(var d=[];a;a=a.nextSibling)a.nodeType===1&&a!==b&&d.push(a);return d}});var Wa=/ jQuery\d+="(?:\d+|null)"/g,Ga=/^\s+/,Xa=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,fb=/<([\w:]+)/,O=/<tbody/i,Ka=/<|&#?\w+;/,la=/<(?:script|object|embed|option|style)/i,
Ha=/checked\s*(?:[^=]|=\s*.checked.)/i,Ja=/\=([^="'>\s]+\/)>/g,V={option:[1,"<select multiple='multiple'>","</select>"],legend:[1,"<fieldset>","</fieldset>"],thead:[1,"<table>","</table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],col:[2,"<table><tbody></tbody><colgroup>","</colgroup></table>"],area:[1,"<map>","</map>"],_default:[0,"",""]};V.optgroup=V.option;V.tbody=V.tfoot=V.colgroup=V.caption=V.thead;V.th=V.td;if(!c.support.htmlSerialize)V._default=
[1,"div<div>","</div>"];c.fn.extend({text:function(a){if(c.isFunction(a))return this.each(function(b){var d=c(this);d.text(a.call(this,b,d.text()))});if(typeof a!=="object"&&a!==A)return this.empty().append((this[0]&&this[0].ownerDocument||v).createTextNode(a));return c.text(this)},wrapAll:function(a){if(c.isFunction(a))return this.each(function(d){c(this).wrapAll(a.call(this,d))});if(this[0]){var b=c(a,this[0].ownerDocument).eq(0).clone(true);this[0].parentNode&&b.insertBefore(this[0]);b.map(function(){for(var d=
this;d.firstChild&&d.firstChild.nodeType===1;)d=d.firstChild;return d}).append(this)}return this},wrapInner:function(a){if(c.isFunction(a))return this.each(function(b){c(this).wrapInner(a.call(this,b))});return this.each(function(){var b=c(this),d=b.contents();d.length?d.wrapAll(a):b.append(a)})},wrap:function(a){return this.each(function(){c(this).wrapAll(a)})},unwrap:function(){return this.parent().each(function(){c.nodeName(this,"body")||c(this).replaceWith(this.childNodes)}).end()},append:function(){return this.domManip(arguments,
true,function(a){this.nodeType===1&&this.appendChild(a)})},prepend:function(){return this.domManip(arguments,true,function(a){this.nodeType===1&&this.insertBefore(a,this.firstChild)})},before:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,false,function(b){this.parentNode.insertBefore(b,this)});else if(arguments.length){var a=c(arguments[0]);a.push.apply(a,this.toArray());return this.pushStack(a,"before",arguments)}},after:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,
false,function(b){this.parentNode.insertBefore(b,this.nextSibling)});else if(arguments.length){var a=this.pushStack(this,"after",arguments);a.push.apply(a,c(arguments[0]).toArray());return a}},remove:function(a,b){for(var d=0,e;(e=this[d])!=null;d++)if(!a||c.filter(a,[e]).length){if(!b&&e.nodeType===1){c.cleanData(e.getElementsByTagName("*"));c.cleanData([e])}e.parentNode&&e.parentNode.removeChild(e)}return this},empty:function(){for(var a=0,b;(b=this[a])!=null;a++)for(b.nodeType===1&&c.cleanData(b.getElementsByTagName("*"));b.firstChild;)b.removeChild(b.firstChild);
return this},clone:function(a){var b=this.map(function(){if(!c.support.noCloneEvent&&!c.isXMLDoc(this)){var d=this.outerHTML,e=this.ownerDocument;if(!d){d=e.createElement("div");d.appendChild(this.cloneNode(true));d=d.innerHTML}return c.clean([d.replace(Wa,"").replace(Ja,'="$1">').replace(Ga,"")],e)[0]}else return this.cloneNode(true)});if(a===true){Ba(this,b);Ba(this.find("*"),b.find("*"))}return b},html:function(a){if(a===A)return this[0]&&this[0].nodeType===1?this[0].innerHTML.replace(Wa,""):null;
else if(typeof a==="string"&&!la.test(a)&&(c.support.leadingWhitespace||!Ga.test(a))&&!V[(fb.exec(a)||["",""])[1].toLowerCase()]){a=a.replace(Xa,"<$1></$2>");try{for(var b=0,d=this.length;b<d;b++)if(this[b].nodeType===1){c.cleanData(this[b].getElementsByTagName("*"));this[b].innerHTML=a}}catch(e){this.empty().append(a)}}else c.isFunction(a)?this.each(function(f){var h=c(this);h.html(a.call(this,f,h.html()))}):this.empty().append(a);return this},replaceWith:function(a){if(this[0]&&this[0].parentNode){if(c.isFunction(a))return this.each(function(b){var d=
c(this),e=d.html();d.replaceWith(a.call(this,b,e))});if(typeof a!=="string")a=c(a).detach();return this.each(function(){var b=this.nextSibling,d=this.parentNode;c(this).remove();b?c(b).before(a):c(d).append(a)})}else return this.pushStack(c(c.isFunction(a)?a():a),"replaceWith",a)},detach:function(a){return this.remove(a,true)},domManip:function(a,b,d){var e,f,h,l=a[0],k=[];if(!c.support.checkClone&&arguments.length===3&&typeof l==="string"&&Ha.test(l))return this.each(function(){c(this).domManip(a,
b,d,true)});if(c.isFunction(l))return this.each(function(u){var F=c(this);a[0]=l.call(this,u,b?F.html():A);F.domManip(a,b,d)});if(this[0]){e=l&&l.parentNode;e=c.support.parentNode&&e&&e.nodeType===11&&e.childNodes.length===this.length?{fragment:e}:c.buildFragment(a,this,k);h=e.fragment;if(f=h.childNodes.length===1?(h=h.firstChild):h.firstChild){b=b&&c.nodeName(f,"tr");for(var o=0,z=this.length;o<z;o++)d.call(b?ca(this[o],f):this[o],o>0||e.cacheable||this.length>1?h.cloneNode(true):h)}k.length&&c.each(k,
da)}return this}});c.buildFragment=function(a,b,d){var e,f,h;b=b&&b[0]?b[0].ownerDocument||b[0]:v;if(a.length===1&&typeof a[0]==="string"&&a[0].length<512&&b===v&&!la.test(a[0])&&(c.support.checkClone||!Ha.test(a[0]))){f=true;if(h=c.fragments[a[0]])if(h!==1)e=h}if(!e){e=b.createDocumentFragment();c.clean(a,b,e,d)}if(f)c.fragments[a[0]]=h?e:1;return{fragment:e,cacheable:f}};c.fragments={};c.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},
function(a,b){c.fn[a]=function(d){var e=[];d=c(d);var f=this.length===1&&this[0].parentNode;if(f&&f.nodeType===11&&f.childNodes.length===1&&d.length===1){d[b](this[0]);return this}else{f=0;for(var h=d.length;f<h;f++){var l=(f>0?this.clone(true):this).get();c(d[f])[b](l);e=e.concat(l)}return this.pushStack(e,a,d.selector)}}});c.extend({clean:function(a,b,d,e){b=b||v;if(typeof b.createElement==="undefined")b=b.ownerDocument||b[0]&&b[0].ownerDocument||v;for(var f=[],h=0,l;(l=a[h])!=null;h++){if(typeof l===
"number")l+="";if(l){if(typeof l==="string"&&!Ka.test(l))l=b.createTextNode(l);else if(typeof l==="string"){l=l.replace(Xa,"<$1></$2>");var k=(fb.exec(l)||["",""])[1].toLowerCase(),o=V[k]||V._default,z=o[0],u=b.createElement("div");for(u.innerHTML=o[1]+l+o[2];z--;)u=u.lastChild;if(!c.support.tbody){z=O.test(l);k=k==="table"&&!z?u.firstChild&&u.firstChild.childNodes:o[1]==="<table>"&&!z?u.childNodes:[];for(o=k.length-1;o>=0;--o)c.nodeName(k[o],"tbody")&&!k[o].childNodes.length&&k[o].parentNode.removeChild(k[o])}!c.support.leadingWhitespace&&
Ga.test(l)&&u.insertBefore(b.createTextNode(Ga.exec(l)[0]),u.firstChild);l=u.childNodes}if(l.nodeType)f.push(l);else f=c.merge(f,l)}}if(d)for(h=0;f[h];h++)if(e&&c.nodeName(f[h],"script")&&(!f[h].type||f[h].type.toLowerCase()==="text/javascript"))e.push(f[h].parentNode?f[h].parentNode.removeChild(f[h]):f[h]);else{f[h].nodeType===1&&f.splice.apply(f,[h+1,0].concat(c.makeArray(f[h].getElementsByTagName("script"))));d.appendChild(f[h])}return f},cleanData:function(a){for(var b,d,e=c.cache,f=c.event.special,
h=c.support.deleteExpando,l=0,k;(k=a[l])!=null;l++)if(!(k.nodeName&&c.noData[k.nodeName.toLowerCase()]))if(d=k[c.expando]){if((b=e[d])&&b.events)for(var o in b.events)f[o]?c.event.remove(k,o):c.removeEvent(k,o,b.handle);if(h)delete k[c.expando];else k.removeAttribute&&k.removeAttribute(c.expando);delete e[d]}}});var oa=/alpha\([^)]*\)/i,Da=/opacity=([^)]*)/,Va=/-([a-z])/ig,jb=/([A-Z])/g,Aa=/^-?\d+(?:px)?$/i,Qa=/^-?\d/,La={position:"absolute",visibility:"hidden",display:"block"},m=["Left","Right"],
q=["Top","Bottom"],w,D,I,aa=function(a,b){return b.toUpperCase()};c.fn.css=function(a,b){if(arguments.length===2&&b===A)return this;return c.access(this,a,b,true,function(d,e,f){return f!==A?c.style(d,e,f):c.css(d,e)})};c.extend({cssHooks:{opacity:{get:function(a,b){if(b){a=w(a,"opacity","opacity");return a===""?"1":a}else return a.style.opacity}}},cssNumber:{zIndex:true,fontWeight:true,opacity:true,zoom:true,lineHeight:true},cssProps:{"float":c.support.cssFloat?"cssFloat":"styleFloat"},style:function(a,
b,d,e){if(!(!a||a.nodeType===3||a.nodeType===8||!a.style)){var f,h=c.camelCase(b),l=a.style,k=c.cssHooks[h];b=c.cssProps[h]||h;if(d!==A){if(!(typeof d==="number"&&isNaN(d)||d==null)){if(typeof d==="number"&&!c.cssNumber[h])d+="px";if(!k||!("set"in k)||(d=k.set(a,d))!==A)try{l[b]=d}catch(o){}}}else{if(k&&"get"in k&&(f=k.get(a,false,e))!==A)return f;return l[b]}}},css:function(a,b,d){var e,f=c.camelCase(b),h=c.cssHooks[f];b=c.cssProps[f]||f;if(h&&"get"in h&&(e=h.get(a,true,d))!==A)return e;else if(w)return w(a,
b,f)},swap:function(a,b,d){var e={};for(var f in b){e[f]=a.style[f];a.style[f]=b[f]}d.call(a);for(f in b)a.style[f]=e[f]},camelCase:function(a){return a.replace(Va,aa)}});c.curCSS=c.css;c.each(["height","width"],function(a,b){c.cssHooks[b]={get:function(d,e,f){var h;if(e){if(d.offsetWidth!==0)h=pa(d,b,f);else c.swap(d,La,function(){h=pa(d,b,f)});if(h<=0){h=w(d,b,b);if(h==="0px"&&I)h=I(d,b,b);if(h!=null)return h===""||h==="auto"?"0px":h}if(h<0||h==null){h=d.style[b];return h===""||h==="auto"?"0px":
h}return typeof h==="string"?h:h+"px"}},set:function(d,e){if(Aa.test(e)){e=parseFloat(e);if(e>=0)return e+"px"}else return e}}});if(!c.support.opacity)c.cssHooks.opacity={get:function(a,b){return Da.test((b&&a.currentStyle?a.currentStyle.filter:a.style.filter)||"")?parseFloat(RegExp.$1)/100+"":b?"1":""},set:function(a,b){a=a.style;a.zoom=1;b=c.isNaN(b)?"":"alpha(opacity="+b*100+")";var d=a.filter||"";a.filter=oa.test(d)?d.replace(oa,b):a.filter+" "+b}};if(v.defaultView&&v.defaultView.getComputedStyle)D=
function(a,b,d){var e;d=d.replace(jb,"-$1").toLowerCase();if(!(b=a.ownerDocument.defaultView))return A;if(b=b.getComputedStyle(a,null)){e=b.getPropertyValue(d);if(e===""&&!c.contains(a.ownerDocument.documentElement,a))e=c.style(a,d)}return e};if(v.documentElement.currentStyle)I=function(a,b){var d,e,f=a.currentStyle&&a.currentStyle[b],h=a.style;if(!Aa.test(f)&&Qa.test(f)){d=h.left;e=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;h.left=b==="fontSize"?"1em":f||0;f=h.pixelLeft+"px";h.left=
d;a.runtimeStyle.left=e}return f===""?"auto":f};w=D||I;if(c.expr&&c.expr.filters){c.expr.filters.hidden=function(a){var b=a.offsetHeight;return a.offsetWidth===0&&b===0||!c.support.reliableHiddenOffsets&&(a.style.display||c.css(a,"display"))==="none"};c.expr.filters.visible=function(a){return!c.expr.filters.hidden(a)}}var ba=c.now(),ia=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,eb=/^(?:select|textarea)/i,kb=/^(?:color|date|datetime|email|hidden|month|number|password|range|search|tel|text|time|url|week)$/i,
sb=/^(?:GET|HEAD)$/,rb=/\[\]$/,Ta=/\=\?(&|$)/,nb=/\?/,tb=/([?&])_=[^&]*/,ub=/^(\w+:)?\/\/([^\/?#]+)/,vb=/%20/g,wb=/#.*$/,pb=c.fn.load;c.fn.extend({load:function(a,b,d){if(typeof a!=="string"&&pb)return pb.apply(this,arguments);else if(!this.length)return this;var e=a.indexOf(" ");if(e>=0){var f=a.slice(e,a.length);a=a.slice(0,e)}e="GET";if(b)if(c.isFunction(b)){d=b;b=null}else if(typeof b==="object"){b=c.param(b,c.ajaxSettings.traditional);e="POST"}var h=this;c.ajax({url:a,type:e,dataType:"html",
data:b,complete:function(l,k){if(k==="success"||k==="notmodified")h.html(f?c("<div>").append(l.responseText.replace(ia,"")).find(f):l.responseText);d&&h.each(d,[l.responseText,k,l])}});return this},serialize:function(){return c.param(this.serializeArray())},serializeArray:function(){return this.map(function(){return this.elements?c.makeArray(this.elements):this}).filter(function(){return this.name&&!this.disabled&&(this.checked||eb.test(this.nodeName)||kb.test(this.type))}).map(function(a,b){a=c(this).val();
return a==null?null:c.isArray(a)?c.map(a,function(d){return{name:b.name,value:d}}):{name:b.name,value:a}}).get()}});c.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){c.fn[b]=function(d){return this.bind(b,d)}});c.extend({get:function(a,b,d,e){if(c.isFunction(b)){e=e||d;d=b;b=null}return c.ajax({type:"GET",url:a,data:b,success:d,dataType:e})},getScript:function(a,b){return c.get(a,null,b,"script")},getJSON:function(a,b,d){return c.get(a,b,d,"json")},post:function(a,
b,d,e){if(c.isFunction(b)){e=e||d;d=b;b={}}return c.ajax({type:"POST",url:a,data:b,success:d,dataType:e})},ajaxSetup:function(a){c.extend(c.ajaxSettings,a)},ajaxSettings:{url:location.href,global:true,type:"GET",contentType:"application/x-www-form-urlencoded",processData:true,async:true,xhr:function(){return new P.XMLHttpRequest},accepts:{xml:"application/xml, text/xml",html:"text/html",script:"text/javascript, application/javascript",json:"application/json, text/javascript",text:"text/plain",_default:"*/*"}},
ajax:function(a){var b=c.extend(true,{},c.ajaxSettings,a),d,e,f,h=b.type.toUpperCase(),l=sb.test(h);b.url=b.url.replace(wb,"");b.context=a&&a.context!=null?a.context:b;if(b.data&&b.processData&&typeof b.data!=="string")b.data=c.param(b.data,b.traditional);if(b.dataType==="jsonp"){if(h==="GET")Ta.test(b.url)||(b.url+=(nb.test(b.url)?"&":"?")+(b.jsonp||"callback")+"=?");else if(!b.data||!Ta.test(b.data))b.data=(b.data?b.data+"&":"")+(b.jsonp||"callback")+"=?";b.dataType="json"}if(b.dataType==="json"&&
(b.data&&Ta.test(b.data)||Ta.test(b.url))){d=b.jsonpCallback||"jsonp"+ba++;if(b.data)b.data=(b.data+"").replace(Ta,"="+d+"$1");b.url=b.url.replace(Ta,"="+d+"$1");b.dataType="script";var k=P[d];P[d]=function(p){if(c.isFunction(k))k(p);else{P[d]=A;try{delete P[d]}catch(r){}}f=p;c.handleSuccess(b,B,e,f);c.handleComplete(b,B,e,f);u&&u.removeChild(F)}}if(b.dataType==="script"&&b.cache===null)b.cache=false;if(b.cache===false&&l){var o=c.now(),z=b.url.replace(tb,"$1_="+o);b.url=z+(z===b.url?(nb.test(b.url)?
"&":"?")+"_="+o:"")}if(b.data&&l)b.url+=(nb.test(b.url)?"&":"?")+b.data;b.global&&c.active++===0&&c.event.trigger("ajaxStart");o=(o=ub.exec(b.url))&&(o[1]&&o[1].toLowerCase()!==location.protocol||o[2].toLowerCase()!==location.host);if(b.dataType==="script"&&h==="GET"&&o){var u=v.getElementsByTagName("head")[0]||v.documentElement,F=v.createElement("script");if(b.scriptCharset)F.charset=b.scriptCharset;F.src=b.url;if(!d){var N=false;F.onload=F.onreadystatechange=function(){if(!N&&(!this.readyState||
this.readyState==="loaded"||this.readyState==="complete")){N=true;c.handleSuccess(b,B,e,f);c.handleComplete(b,B,e,f);F.onload=F.onreadystatechange=null;u&&F.parentNode&&u.removeChild(F)}}}u.insertBefore(F,u.firstChild);return A}var ga=false,B=b.xhr();if(B){b.username?B.open(h,b.url,b.async,b.username,b.password):B.open(h,b.url,b.async);try{if(b.data!=null&&!l||a&&a.contentType)B.setRequestHeader("Content-Type",b.contentType);if(b.ifModified){c.lastModified[b.url]&&B.setRequestHeader("If-Modified-Since",
c.lastModified[b.url]);c.etag[b.url]&&B.setRequestHeader("If-None-Match",c.etag[b.url])}o||B.setRequestHeader("X-Requested-With","XMLHttpRequest");B.setRequestHeader("Accept",b.dataType&&b.accepts[b.dataType]?b.accepts[b.dataType]+", */*; q=0.01":b.accepts._default)}catch(fa){}if(b.beforeSend&&b.beforeSend.call(b.context,B,b)===false){b.global&&c.active--===1&&c.event.trigger("ajaxStop");B.abort();return false}b.global&&c.triggerGlobal(b,"ajaxSend",[B,b]);var ua=B.onreadystatechange=function(p){if(!B||
B.readyState===0||p==="abort"){ga||c.handleComplete(b,B,e,f);ga=true;if(B)B.onreadystatechange=c.noop}else if(!ga&&B&&(B.readyState===4||p==="timeout")){ga=true;B.onreadystatechange=c.noop;e=p==="timeout"?"timeout":!c.httpSuccess(B)?"error":b.ifModified&&c.httpNotModified(B,b.url)?"notmodified":"success";var r;if(e==="success")try{f=c.httpData(B,b.dataType,b)}catch(t){e="parsererror";r=t}if(e==="success"||e==="notmodified")d||c.handleSuccess(b,B,e,f);else c.handleError(b,B,e,r);d||c.handleComplete(b,
B,e,f);p==="timeout"&&B.abort();if(b.async)B=null}};try{var g=B.abort;B.abort=function(){B&&Function.prototype.call.call(g,B);ua("abort")}}catch(i){}b.async&&b.timeout>0&&setTimeout(function(){B&&!ga&&ua("timeout")},b.timeout);try{B.send(l||b.data==null?null:b.data)}catch(n){c.handleError(b,B,null,n);c.handleComplete(b,B,e,f)}b.async||ua();return B}},param:function(a,b){var d=[],e=function(h,l){l=c.isFunction(l)?l():l;d[d.length]=encodeURIComponent(h)+"="+encodeURIComponent(l)};if(b===A)b=c.ajaxSettings.traditional;
if(c.isArray(a)||a.jquery)c.each(a,function(){e(this.name,this.value)});else for(var f in a)ya(f,a[f],b,e);return d.join("&").replace(vb,"+")}});c.extend({active:0,lastModified:{},etag:{},handleError:function(a,b,d,e){a.error&&a.error.call(a.context,b,d,e);a.global&&c.triggerGlobal(a,"ajaxError",[b,a,e])},handleSuccess:function(a,b,d,e){a.success&&a.success.call(a.context,e,d,b);a.global&&c.triggerGlobal(a,"ajaxSuccess",[b,a])},handleComplete:function(a,b,d){a.complete&&a.complete.call(a.context,
b,d);a.global&&c.triggerGlobal(a,"ajaxComplete",[b,a]);a.global&&c.active--===1&&c.event.trigger("ajaxStop")},triggerGlobal:function(a,b,d){(a.context&&a.context.url==null?c(a.context):c.event).trigger(b,d)},httpSuccess:function(a){try{return!a.status&&location.protocol==="file:"||a.status>=200&&a.status<300||a.status===304||a.status===1223}catch(b){}return false},httpNotModified:function(a,b){var d=a.getResponseHeader("Last-Modified"),e=a.getResponseHeader("Etag");if(d)c.lastModified[b]=d;if(e)c.etag[b]=
e;return a.status===304},httpData:function(a,b,d){var e=a.getResponseHeader("content-type")||"",f=b==="xml"||!b&&e.indexOf("xml")>=0;a=f?a.responseXML:a.responseText;f&&a.documentElement.nodeName==="parsererror"&&c.error("parsererror");if(d&&d.dataFilter)a=d.dataFilter(a,b);if(typeof a==="string")if(b==="json"||!b&&e.indexOf("json")>=0)a=c.parseJSON(a);else if(b==="script"||!b&&e.indexOf("javascript")>=0)c.globalEval(a);return a}});if(P.ActiveXObject)c.ajaxSettings.xhr=function(){if(P.location.protocol!==
"file:")try{return new P.XMLHttpRequest}catch(a){}try{return new P.ActiveXObject("Microsoft.XMLHTTP")}catch(b){}};c.support.ajax=!!c.ajaxSettings.xhr();var lb={},xb=/^(?:toggle|show|hide)$/,yb=/^([+\-]=)?([\d+.\-]+)(.*)$/,ib,ob=[["height","marginTop","marginBottom","paddingTop","paddingBottom"],["width","marginLeft","marginRight","paddingLeft","paddingRight"],["opacity"]];c.fn.extend({show:function(a,b,d){if(a||a===0)return this.animate(ma("show",3),a,b,d);else{d=0;for(var e=this.length;d<e;d++){a=
this[d];b=a.style.display;if(!c.data(a,"olddisplay")&&b==="none")b=a.style.display="";b===""&&c.css(a,"display")==="none"&&c.data(a,"olddisplay",ka(a.nodeName))}for(d=0;d<e;d++){a=this[d];b=a.style.display;if(b===""||b==="none")a.style.display=c.data(a,"olddisplay")||""}return this}},hide:function(a,b,d){if(a||a===0)return this.animate(ma("hide",3),a,b,d);else{a=0;for(b=this.length;a<b;a++){d=c.css(this[a],"display");d!=="none"&&c.data(this[a],"olddisplay",d)}for(a=0;a<b;a++)this[a].style.display=
"none";return this}},_toggle:c.fn.toggle,toggle:function(a,b,d){var e=typeof a==="boolean";if(c.isFunction(a)&&c.isFunction(b))this._toggle.apply(this,arguments);else a==null||e?this.each(function(){var f=e?a:c(this).is(":hidden");c(this)[f?"show":"hide"]()}):this.animate(ma("toggle",3),a,b,d);return this},fadeTo:function(a,b,d,e){return this.filter(":hidden").css("opacity",0).show().end().animate({opacity:b},a,d,e)},animate:function(a,b,d,e){var f=c.speed(b,d,e);if(c.isEmptyObject(a))return this.each(f.complete);
return this[f.queue===false?"each":"queue"](function(){var h=c.extend({},f),l,k=this.nodeType===1,o=k&&c(this).is(":hidden"),z=this;for(l in a){var u=c.camelCase(l);if(l!==u){a[u]=a[l];delete a[l];l=u}if(a[l]==="hide"&&o||a[l]==="show"&&!o)return h.complete.call(this);if(k&&(l==="height"||l==="width")){h.overflow=[this.style.overflow,this.style.overflowX,this.style.overflowY];if(c.css(this,"display")==="inline"&&c.css(this,"float")==="none")if(c.support.inlineBlockNeedsLayout)if(ka(this.nodeName)===
"inline")this.style.display="inline-block";else{this.style.display="inline";this.style.zoom=1}else this.style.display="inline-block"}if(c.isArray(a[l])){(h.specialEasing=h.specialEasing||{})[l]=a[l][1];a[l]=a[l][0]}}if(h.overflow!=null)this.style.overflow="hidden";h.curAnim=c.extend({},a);c.each(a,function(F,N){var ga=new c.fx(z,h,F);if(xb.test(N))ga[N==="toggle"?o?"show":"hide":N](a);else{var B=yb.exec(N),fa=ga.cur()||0;if(B){N=parseFloat(B[2]);var ua=B[3]||"px";if(ua!=="px"){c.style(z,F,(N||1)+
ua);fa=(N||1)/ga.cur()*fa;c.style(z,F,fa+ua)}if(B[1])N=(B[1]==="-="?-1:1)*N+fa;ga.custom(fa,N,ua)}else ga.custom(fa,N,"")}});return true})},stop:function(a,b){var d=c.timers;a&&this.queue([]);this.each(function(){for(var e=d.length-1;e>=0;e--)if(d[e].elem===this){b&&d[e](true);d.splice(e,1)}});b||this.dequeue();return this}});c.each({slideDown:ma("show",1),slideUp:ma("hide",1),slideToggle:ma("toggle",1),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"},fadeToggle:{opacity:"toggle"}},function(a,b){c.fn[a]=
function(d,e,f){return this.animate(b,d,e,f)}});c.extend({speed:function(a,b,d){var e=a&&typeof a==="object"?c.extend({},a):{complete:d||!d&&b||c.isFunction(a)&&a,duration:a,easing:d&&b||b&&!c.isFunction(b)&&b};e.duration=c.fx.off?0:typeof e.duration==="number"?e.duration:e.duration in c.fx.speeds?c.fx.speeds[e.duration]:c.fx.speeds._default;e.old=e.complete;e.complete=function(){e.queue!==false&&c(this).dequeue();c.isFunction(e.old)&&e.old.call(this)};return e},easing:{linear:function(a,b,d,e){return d+
e*a},swing:function(a,b,d,e){return(-Math.cos(a*Math.PI)/2+0.5)*e+d}},timers:[],fx:function(a,b,d){this.options=b;this.elem=a;this.prop=d;if(!b.orig)b.orig={}}});c.fx.prototype={update:function(){this.options.step&&this.options.step.call(this.elem,this.now,this);(c.fx.step[this.prop]||c.fx.step._default)(this)},cur:function(){if(this.elem[this.prop]!=null&&(!this.elem.style||this.elem.style[this.prop]==null))return this.elem[this.prop];var a=parseFloat(c.css(this.elem,this.prop));return a&&a>-10000?
a:0},custom:function(a,b,d){function e(l){return f.step(l)}var f=this,h=c.fx;this.startTime=c.now();this.start=a;this.end=b;this.unit=d||this.unit||"px";this.now=this.start;this.pos=this.state=0;e.elem=this.elem;if(e()&&c.timers.push(e)&&!ib)ib=setInterval(h.tick,h.interval)},show:function(){this.options.orig[this.prop]=c.style(this.elem,this.prop);this.options.show=true;this.custom(this.prop==="width"||this.prop==="height"?1:0,this.cur());c(this.elem).show()},hide:function(){this.options.orig[this.prop]=
c.style(this.elem,this.prop);this.options.hide=true;this.custom(this.cur(),0)},step:function(a){var b=c.now(),d=true;if(a||b>=this.options.duration+this.startTime){this.now=this.end;this.pos=this.state=1;this.update();this.options.curAnim[this.prop]=true;for(var e in this.options.curAnim)if(this.options.curAnim[e]!==true)d=false;if(d){if(this.options.overflow!=null&&!c.support.shrinkWrapBlocks){var f=this.elem,h=this.options;c.each(["","X","Y"],function(k,o){f.style["overflow"+o]=h.overflow[k]})}this.options.hide&&
c(this.elem).hide();if(this.options.hide||this.options.show)for(var l in this.options.curAnim)c.style(this.elem,l,this.options.orig[l]);this.options.complete.call(this.elem)}return false}else{a=b-this.startTime;this.state=a/this.options.duration;b=this.options.easing||(c.easing.swing?"swing":"linear");this.pos=c.easing[this.options.specialEasing&&this.options.specialEasing[this.prop]||b](this.state,a,0,1,this.options.duration);this.now=this.start+(this.end-this.start)*this.pos;this.update()}return true}};
c.extend(c.fx,{tick:function(){for(var a=c.timers,b=0;b<a.length;b++)a[b]()||a.splice(b--,1);a.length||c.fx.stop()},interval:13,stop:function(){clearInterval(ib);ib=null},speeds:{slow:600,fast:200,_default:400},step:{opacity:function(a){c.style(a.elem,"opacity",a.now)},_default:function(a){if(a.elem.style&&a.elem.style[a.prop]!=null)a.elem.style[a.prop]=(a.prop==="width"||a.prop==="height"?Math.max(0,a.now):a.now)+a.unit;else a.elem[a.prop]=a.now}}});if(c.expr&&c.expr.filters)c.expr.filters.animated=
function(a){return c.grep(c.timers,function(b){return a===b.elem}).length};var zb=/^t(?:able|d|h)$/i,qb=/^(?:body|html)$/i;c.fn.offset="getBoundingClientRect"in v.documentElement?function(a){var b=this[0],d;if(a)return this.each(function(l){c.offset.setOffset(this,a,l)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);try{d=b.getBoundingClientRect()}catch(e){}var f=b.ownerDocument,h=f.documentElement;if(!d||!c.contains(h,b))return d||{top:0,left:0};b=
f.body;f=qa(f);return{top:d.top+(f.pageYOffset||c.support.boxModel&&h.scrollTop||b.scrollTop)-(h.clientTop||b.clientTop||0),left:d.left+(f.pageXOffset||c.support.boxModel&&h.scrollLeft||b.scrollLeft)-(h.clientLeft||b.clientLeft||0)}}:function(a){var b=this[0];if(a)return this.each(function(u){c.offset.setOffset(this,a,u)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);c.offset.initialize();var d,e=b.offsetParent,f=b,h=b.ownerDocument,l=h.documentElement,
k=h.body;d=(h=h.defaultView)?h.getComputedStyle(b,null):b.currentStyle;for(var o=b.offsetTop,z=b.offsetLeft;(b=b.parentNode)&&b!==k&&b!==l;){if(c.offset.supportsFixedPosition&&d.position==="fixed")break;d=h?h.getComputedStyle(b,null):b.currentStyle;o-=b.scrollTop;z-=b.scrollLeft;if(b===e){o+=b.offsetTop;z+=b.offsetLeft;if(c.offset.doesNotAddBorder&&!(c.offset.doesAddBorderForTableAndCells&&zb.test(b.nodeName))){o+=parseFloat(d.borderTopWidth)||0;z+=parseFloat(d.borderLeftWidth)||0}f=e;e=b.offsetParent}if(c.offset.subtractsBorderForOverflowNotVisible&&
d.overflow!=="visible"){o+=parseFloat(d.borderTopWidth)||0;z+=parseFloat(d.borderLeftWidth)||0}d=d}if(d.position==="relative"||d.position==="static"){o+=k.offsetTop;z+=k.offsetLeft}if(c.offset.supportsFixedPosition&&d.position==="fixed"){o+=Math.max(l.scrollTop,k.scrollTop);z+=Math.max(l.scrollLeft,k.scrollLeft)}return{top:o,left:z}};c.offset={initialize:function(){var a=v.body,b=v.createElement("div"),d,e,f,h=parseFloat(c.css(a,"marginTop"))||0;c.extend(b.style,{position:"absolute",top:0,left:0,
margin:0,border:0,width:"1px",height:"1px",visibility:"hidden"});b.innerHTML="<div style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;'><div></div></div><table style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;' cellpadding='0' cellspacing='0'><tr><td></td></tr></table>";a.insertBefore(b,a.firstChild);d=b.firstChild;e=d.firstChild;f=d.nextSibling.firstChild.firstChild;this.doesNotAddBorder=e.offsetTop!==
5;this.doesAddBorderForTableAndCells=f.offsetTop===5;e.style.position="fixed";e.style.top="20px";this.supportsFixedPosition=e.offsetTop===20||e.offsetTop===15;e.style.position=e.style.top="";d.style.overflow="hidden";d.style.position="relative";this.subtractsBorderForOverflowNotVisible=e.offsetTop===-5;this.doesNotIncludeMarginInBodyOffset=a.offsetTop!==h;a.removeChild(b);c.offset.initialize=c.noop},bodyOffset:function(a){var b=a.offsetTop,d=a.offsetLeft;c.offset.initialize();if(c.offset.doesNotIncludeMarginInBodyOffset){b+=
parseFloat(c.css(a,"marginTop"))||0;d+=parseFloat(c.css(a,"marginLeft"))||0}return{top:b,left:d}},setOffset:function(a,b,d){var e=c.css(a,"position");if(e==="static")a.style.position="relative";var f=c(a),h=f.offset(),l=c.css(a,"top"),k=c.css(a,"left"),o=e==="absolute"&&c.inArray("auto",[l,k])>-1;e={};var z={};if(o)z=f.position();l=o?z.top:parseInt(l,10)||0;k=o?z.left:parseInt(k,10)||0;if(c.isFunction(b))b=b.call(a,d,h);if(b.top!=null)e.top=b.top-h.top+l;if(b.left!=null)e.left=b.left-h.left+k;"using"in
b?b.using.call(a,e):f.css(e)}};c.fn.extend({position:function(){if(!this[0])return null;var a=this[0],b=this.offsetParent(),d=this.offset(),e=qb.test(b[0].nodeName)?{top:0,left:0}:b.offset();d.top-=parseFloat(c.css(a,"marginTop"))||0;d.left-=parseFloat(c.css(a,"marginLeft"))||0;e.top+=parseFloat(c.css(b[0],"borderTopWidth"))||0;e.left+=parseFloat(c.css(b[0],"borderLeftWidth"))||0;return{top:d.top-e.top,left:d.left-e.left}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||
v.body;a&&!qb.test(a.nodeName)&&c.css(a,"position")==="static";)a=a.offsetParent;return a})}});c.each(["Left","Top"],function(a,b){var d="scroll"+b;c.fn[d]=function(e){var f=this[0],h;if(!f)return null;if(e!==A)return this.each(function(){if(h=qa(this))h.scrollTo(!a?e:c(h).scrollLeft(),a?e:c(h).scrollTop());else this[d]=e});else return(h=qa(f))?"pageXOffset"in h?h[a?"pageYOffset":"pageXOffset"]:c.support.boxModel&&h.document.documentElement[d]||h.document.body[d]:f[d]}});c.each(["Height","Width"],
function(a,b){var d=b.toLowerCase();c.fn["inner"+b]=function(){return this[0]?parseFloat(c.css(this[0],d,"padding")):null};c.fn["outer"+b]=function(e){return this[0]?parseFloat(c.css(this[0],d,e?"margin":"border")):null};c.fn[d]=function(e){var f=this[0];if(!f)return e==null?null:this;if(c.isFunction(e))return this.each(function(l){var k=c(this);k[d](e.call(this,l,k[d]()))});if(c.isWindow(f))return f.document.compatMode==="CSS1Compat"&&f.document.documentElement["client"+b]||f.document.body["client"+
b];else if(f.nodeType===9)return Math.max(f.documentElement["client"+b],f.body["scroll"+b],f.documentElement["scroll"+b],f.body["offset"+b],f.documentElement["offset"+b]);else if(e===A){f=c.css(f,d);var h=parseFloat(f);return c.isNaN(h)?f:h}else return this.css(d,typeof e==="string"?e:e+"px")}});typeof define!=="undefined"&&define("jquery",[],function(){return c})})(window);